'use client';
import { useEffect, useRef, useState } from 'react';
import { Box, Glasses, Upload, RotateCcw, ArrowUpRight, CircleHelp, X, Layers3, RefreshCw, Maximize2 } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { Gallery } from './vrscene';
const demos=[{id:'sculpture',name:'Пластика формы',tag:'01 · СКУЛЬПТУРА'},{id:'robot',name:'Робот-манипулятор',tag:'02 · МЕХАНИЗМ'},{id:'orbit',name:'Орбитальная система',tag:'03 · КИНЕТИКА'}];
export default function Home(){
 const host=useRef<HTMLDivElement>(null), api=useRef<Gallery|null>(null), input=useRef<HTMLInputElement>(null);
 const [ready,setReady]=useState(false),[xr,setXR]=useState('Проверяем гарнитуру…'),[supports,setSupports]=useState<boolean|undefined>(),[selected,setSelected]=useState('sculpture'),[name,setName]=useState('Пластика формы'),[scale,setScale]=useState(1),[spin,setSpin]=useState(true),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[help,setHelp]=useState(false),[inVR,setInVR]=useState(false),[panel,setPanel]=useState(true);
 useEffect(()=>{let alive=true;import('./vrscene').then(({createGallery})=>{if(!alive||!host.current)return;api.current=createGallery(host.current,{onVR:setInVR,onState:(s)=>{setScale(s.scale);setSpin(s.spin);},onError:setMessage});setReady(true);}).catch(()=>setMessage('Не удалось запустить 3D. Обновите страницу в браузере с поддержкой WebGL.'));const nav=navigator as Navigator & {xr?:{isSessionSupported:(s:string)=>Promise<boolean>}};if(nav.xr&&window.isSecureContext)nav.xr.isSessionSupported('immersive-vr').then(v=>{setSupports(v);setXR(v?'Гарнитура готова к VR':'3D-режим · откройте на Quest');}).catch(()=>setXR('Откройте сайт в Meta Quest Browser'));else setXR('3D-режим · откройте на Quest');return()=>{alive=false;api.current?.dispose();api.current=null;};},[]);
 function pick(id:string){if(!api.current||busy)return;api.current.demo(id);setSelected(id);setName(demos.find(d=>d.id===id)?.name||id);setScale(1);setSpin(true);setMessage('');history.replaceState(null,'',location.pathname+'?gallery=1');}
 async function upload(file?:File){if(!file||!api.current||busy)return;const ext=file.name.split('.').pop()?.toLowerCase();if(!['glb','stl'].includes(ext||'')){setMessage('Выберите файл GLB или STL.');return;}if(file.size>20*1024*1024){setMessage('Для MVP выберите модель до 20 МБ.');return;}setBusy(true);setMessage('Проверяем модель…');try{const bytes=await file.arrayBuffer();await api.current.load(bytes,ext!);setName(file.name);setSelected('local');setScale(1);setSpin(false);history.replaceState(null,'',location.pathname+'?gallery=1');setMessage('Модель открыта на этом устройстве. Файл не отправляется в интернет.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
 async function enterVR(){if(!api.current)return;try{await api.current.enterVR();setSupports(true);setXR('VR-сеанс запущен');}catch(e){setMessage('Не удалось войти в VR. '+(e as Error).message);}}
 useEffect(()=>{if(!ready)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'select_demo_model',description:'Выбрать демонстрационный объект в VR-галерее.',inputSchema:{type:'object',properties:{id:{type:'string',enum:['sculpture','robot','orbit']}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({id}:any)=>{if(!demos.some(d=>d.id===id)||busy)throw new Error('Недопустимый объект или загрузка в процессе');pick(id);return {selected:id};}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[ready,busy]);
 return <main className={'app '+(inVR?'immersed':'')}>
 <header className="topbar"><a className="brand" href="./" aria-label="Технопарк VR — главная"><span className="brand-icon"><Box size={24}/></span><span>ТЕХНОПАРК<span className="brand-sub">VR / ПРОСТРАНСТВО</span></span></a><div className="top-right"><button className="header-vr" onClick={()=>void enterVR()} disabled={!ready||busy}><Glasses size={20}/><span className="header-vr-text">Войти в </span>VR</button><span className="mode-label">ИНТЕРАКТИВНАЯ ГАЛЕРЕЯ</span><button className="icon-btn" aria-label="Как пользоваться" onClick={()=>setHelp(!help)}><CircleHelp size={21}/></button></div></header>
 <div className="workspace">
 <section className="viewport" aria-label="Трехмерная сцена"><div ref={host} className="scene"/><div className="scene-heading"><span className="eyebrow">ЭКСПОЗИЦИЯ / {selected==='sculpture'?'01':selected==='robot'?'02':selected==='orbit'?'03':'04'}</span><h1>{name}</h1><p>Исследуйте пространство в своем масштабе.</p></div>
 {!ready&&<div className="scene-loading">{message||'Создаем пространство…'}</div>}
 <button className="panel-toggle icon-btn" aria-label="Показать или скрыть настройки" onClick={()=>setPanel(!panel)}><Layers3 size={22}/></button>
 <div className="scene-bottom"><span><span className="key">↔</span> Вращайте мышью или пальцем <span className="desktop-hint"> · Колесо — приближение</span></span><button className="icon-btn" title="Вернуть обзор" aria-label="Вернуть обзор" onClick={()=>api.current?.resetView()}><Maximize2 size={19}/></button></div>
 <div className="scene-mark">WEBXR LAB <span>—</span> 001</div></section>
 <aside className={'panel '+(!panel?'panel-closed':'')}><div className="panel-intro"><span className="eyebrow">КОЛЛЕКЦИЯ</span><h2>Выберите объект</h2><p>Начните с демо или добавьте свою модель.</p></div>
 <div className="demo-list">{demos.map((d,i)=><button key={d.id} className={'demo '+(selected===d.id?'active':'')} onClick={()=>pick(d.id)} disabled={!ready||busy}><span className={'demo-symbol symbol-'+i}>{i===0?'∞':i===1?'⌁':'◎'}</span><span><small>{d.tag}</small><strong>{d.name}</strong></span>{selected===d.id&&<ArrowUpRight size={19}/>}</button>)}</div>
 <div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files[0]);}}><button onClick={()=>input.current?.click()} disabled={!ready||busy} className="upload-btn"><Upload size={19}/>{busy?'Загрузка…':'Открыть свою модель'}</button><input ref={input} type="file" accept=".glb,.stl" onChange={e=>void upload(e.target.files?.[0])} hidden/><p>GLB или STL · до 20 МБ<br/>Открывается на этом устройстве</p></div>
 <div className="settings"><div className="setting-label"><label id="scale-label">Масштаб объекта</label><span>{scale.toFixed(1)}×</span></div><Slider aria-labelledby="scale-label" min={0.3} max={3} step={0.1} value={[scale]} disabled={!ready||busy} onValueChange={v=>{setScale(v[0]);api.current?.scale(v[0]);}}/><div className="setting-label spin-row"><label htmlFor="spin">Автовращение</label><Switch id="spin" checked={spin} disabled={!ready||busy} onCheckedChange={v=>{setSpin(v);api.current?.spin(v);}}/></div><button className="reset-btn" onClick={()=>{api.current?.resetModel();setScale(1);setSpin(false);}} disabled={!ready||busy}><RotateCcw size={15}/>Сбросить положение</button><p className="scale-note">Модель вписывается в витрину. Масштаб условный.</p></div>
 <div className="vr-block"><div className="xr-status"><Glasses size={16}/>{xr}</div><button className="vr-btn" onClick={()=>void enterVR()} disabled={!ready||busy}><Glasses size={22}/>{supports===false?'Попробовать VR':'Войти в VR'}<ArrowUpRight size={20}/></button><p>Meta Quest Browser · вход одним нажатием</p></div>
 </aside></div>
 {message&&<div role="status" className="notice"><span>{message}</span><button className="icon-btn" aria-label="Закрыть уведомление" onClick={()=>setMessage('')}><X size={17}/></button></div>}
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-box" showCloseButton={false}><button autoFocus className="icon-btn close-help" aria-label="Закрыть инструкцию" onClick={()=>setHelp(false)}><X/></button><Glasses size={35}/><DialogTitle>Вы уже на пороге VR</DialogTitle><DialogDescription className="sr-only">Инструкция для Meta Quest и загрузки моделей.</DialogDescription><ol><li>Откройте эту страницу в <b>Meta Quest Browser</b>. Вход в аккаунт не требуется.</li><li>Выберите объект и нажмите <b>«Войти в VR»</b>. Подтвердите запрос браузера.</li><li>Наведите луч контроллера на круг на полу и нажмите курок — вы переместитесь к нему.</li><li>Кнопки перед постаментом меняют масштаб и вращение. Правый стик поворачивает обзор шагами.</li></ol><p>Для своей модели: выберите файл, который находится на текущем устройстве. Чтобы открыть его на Quest, сначала скопируйте файл в очки. Загрузки между устройствами не синхронизируются. GLB — с текстурами внутри файла; STL — геометрия без цвета. Выход из VR — через системную кнопку Meta.</p><button className="vr-btn" onClick={()=>{navigator.clipboard?.writeText(location.href).then(()=>setMessage('Ссылка скопирована.')).catch(()=>setMessage('Скопируйте адрес из строки браузера.'));}}>Скопировать ссылку</button></DialogContent></Dialog>
 </main>;
}
