import React,{useEffect,useRef,useState} from 'react';
import {createExperience} from './worldEngine';
export default function Experience(){
 const host=useRef<HTMLDivElement>(null),game=useRef<ReturnType<typeof createExperience>|null>(null);
 const [scene,setScene]=useState('hub'),[status,setStatus]=useState('Подготовка пространства…'),[error,setError]=useState(''),[entering,setEntering]=useState(false),[help,setHelp]=useState(false),[muted,setMuted]=useState(false),[clean,setClean]=useState(false),[presentation,setPresentation]=useState(false);
 async function enterVR(){if(entering)return;if(!game.current){setError('3D-сцена не запустилась. Обновите страницу и проверьте сообщение об ошибке.');return;}setEntering(true);try{await game.current.enterVR();setError('');}catch(e){setError('Вход в VR: '+(e instanceof Error?e.message:String(e)));}finally{setEntering(false);}}
 useEffect(()=>{try{game.current=createExperience(host.current!,{status:setStatus,scene:setScene,presentation:setPresentation});}catch(e){setError('Не удалось запустить 3D: '+String(e));}return()=>game.current?.dispose();},[]);
 const hub=scene==='hub';
 return <div className={'experience '+(hub?'is-hub':'is-game')+(clean?' clean':'')}>
 <div ref={host} className="world"/>
 <header className="game-header"><a href="?v=6" className="wordmark"><i>Т.</i><div>ТЕХНОПАРК<span>РГСУ / IMMERSIVE LAB</span></div></a><div className="header-tools"><span className="live-badge">EXPERIENCE 006</span><button onClick={()=>setMuted(game.current?.toggleSound()??false)}>{muted?'Звук выкл.':'♪ Звук вкл.'}</button><button onClick={()=>setHelp(true)}>Как играть ?</button><button onClick={()=>game.current?.setPresentation(!presentation)}>{presentation?'Показ ∞ включён':'Режим показа'}</button><button onClick={()=>setClean(!clean)}>{clean?'Вернуть интерфейс':'Чистый вид ↗'}</button></div></header>
 {!clean&&<><main className="game-overlay"><div className="eyebrow"><span/> {hub?'ПРОСТРАНСТВО ВОЗМОЖНОСТЕЙ':scene==='robot'?'01 / ROBOT ARENA':'02 / AERIAL LAB'}</div><h1>{hub?<>Искусство.<br/>Технологии.<br/><em>Вы внутри.</em></>:scene==='robot'?<>Красный<br/><em>треугольник.</em></>:<>Точность.<br/><em>Реакция.</em></>}</h1><p>{hub?'Кинетическое «Ядро», два портала и инженерные испытания. Исследуйте пространство в своём темпе.':scene==='robot'?'Кольцевой спиннер команды «Дезинтегратор». Соберите 5 энергоячеек, уничтожьте 6 блоков и победите «Бульдозер» в финальной дуэли.':'Три ступени скорости. Серии попаданий увеличивают множитель до ×4. Шесть зарядов — каждый имеет значение.'}</p>{!hub&&<div className="round-actions"><button className="start-round" onClick={()=>game.current?.start()}>Начать раунд / пропустить урок →</button><button onClick={()=>game.current?.train()}>Пройти обучение</button></div>}</main>
 <aside className="game-status"><span className="status-label">{hub?'LIVE INSTALLATION':'ТЕЛЕМЕТРИЯ'}</span><strong>{status}</strong></aside>
 {hub&&<section className="portal-cards"><button onClick={()=>game.current?.go('robot')}><span className="card-number">01 / КОНТРОЛЬ</span><strong>Робот-арена <b>↗</b></strong><small>Спиннер · энергоячейки · финальная дуэль</small></button><button onClick={()=>game.current?.go('drones')}><span className="card-number">02 / РЕАКЦИЯ</span><strong>Дрон-тир <b>↗</b></strong><small>Точность · серии попаданий · рекорд</small></button></section>}
 <footer className="game-footer"><span>{hub?'WASD — движение · Потяните мышью — осмотр · Q / E — поворот':scene==='robot'?'W / S — ход · A / D — поворот робота · Пробел — спиннер':'Наведите курсор и нажмите — выстрел · R — перезарядка'}</span><nav><button onClick={()=>{game.current?.nextVisitor();setClean(false);}}>Новый посетитель</button>{!hub&&<><button onClick={()=>game.current?.restart()}>↻ Сброс</button><button onClick={()=>game.current?.go('hub')}>⌂ Холл</button></>}<a href="?gallery=1">3D-галерея ↗</a></nav></footer>
 {scene==='robot'&&<div className="touch-controls">{[['↑','w'],['←','a'],['↓','s'],['→','d']].map(([label,key])=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);game.current?.key(key,true);}} onPointerUp={()=>game.current?.key(key,false)} onPointerCancel={()=>game.current?.key(key,false)}>{label}</button>)}<button onClick={()=>game.current?.spin()}>Спиннер</button></div>}
 {scene==='drones'&&<button className="reload" onClick={()=>game.current?.reload()}>Перезарядка / R</button>}
 </>}
 <div className="vr-entry"><button disabled={entering} onClick={enterVR}>{entering?'Подключение…':'◉ Войти в VR'}</button><span>QUEST · WEBXR · ВЕРСИЯ 6</span></div>
 {help&&<div className="help-scrim"><section className="help-panel"><button className="close-help" onClick={()=>setHelp(false)}>Закрыть ×</button><div className="eyebrow">КРАТКИЙ ИНСТРУКТАЖ</div><h2>Всё под рукой.</h2><div className="help-grid"><article><h3>В очках</h3><p>Левый стик: перемещение в холле или управление роботом. Правый стик: поворот на 30°. Луч + курок: выбрать портал или кнопку.</p><p>Правый курок: старт, спиннер или выстрел. Правая боковая кнопка: перезарядка. Левая боковая кнопка: вернуться в холл.</p><p>Световые круги на полу: телепортация по нажатию курка. Раунд начинается только после команды, с отсчётом 3–2–1.</p></article><article><h3>На компьютере</h3><p>Холл: WASD — ходьба, перетаскивание мышью — осмотр, Q/E — поворот. Нажмите портал для входа.</p><p>Робот: W/S — вперёд и назад, A/D — руление, пробел — старт или спиннер. Тир: клик по цели, R — перезарядка.</p><p>За три попадания подряд растёт множитель. Промах сбрасывает серию. Рекорды сохраняются в этом браузере. В режиме показа нет таймера, очки не попадают в рекорды. Кнопка «Новый посетитель» возвращает в холл и повторяет обучение, сохраняя режим показа.</p></article></div><button className="start-round" onClick={()=>setHelp(false)}>Всё понятно →</button></section></div>}
 {error&&<div className="game-error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}
 </div>;
}
