import React,{useEffect,useRef,useState} from 'react';
import {createExperience} from './worldEngine';
export default function Experience(){
 const host=useRef<HTMLDivElement>(null),game=useRef<ReturnType<typeof createExperience>|null>(null),dialog=useRef<HTMLDialogElement>(null);
 const [scene,setScene]=useState('hub'),[status,setStatus]=useState('Подготовка пространства…'),[error,setError]=useState('');
 const [entering,setEntering]=useState(false),[help,setHelp]=useState(false),[menu,setMenu]=useState(false),[muted,setMuted]=useState(false),[clean,setClean]=useState(false),[presentation,setPresentation]=useState(false),[fullscreen,setFullscreen]=useState(false),[online,setOnline]=useState(()=>navigator.onLine),[autoDemo,setAutoDemo]=useState(false);
 const [paused,setPaused]=useState(false),[xr,setXR]=useState(false),[supported,setSupported]=useState<boolean>(),[phase,setPhase]=useState('hub'),[action,setAction]=useState('Захватить груз'),[hint,setHint]=useState(''),[diagnostics,setDiagnostics]=useState(''),[records,setRecords]=useState<Record<string,number>>({robot:0,drones:0,cargo:0});
 const [showDiagnostics,setShowDiagnostics]=useState(()=>new URLSearchParams(location.search).has('diagnostics'));
 const menuButton=useRef<HTMLButtonElement>(null),menuPausedByUs=useRef(false),wakeLock=useRef<any>(null);
 const hub=scene==='hub',cargo=scene==='cargo',ground=cargo||scene==='robot',busy=action.includes('работает');
 const title=hub?'VR-пространство':cargo?'Полигон Лосинка':scene==='robot'?'Робот-арена':'Дрон-тир';
 const sceneMeta=scene==='cargo'?{num:'03',tag:'ЛОГИСТИКА',objective:'3 ГРУЗА',control:'ЛЕВЫЙ СТИК + КУРОК'}:scene==='robot'?{num:'01',tag:'КОНТРОЛЬ',objective:'5 + 6 + ДУЭЛЬ',control:'ЛЕВЫЙ СТИК + КУРОК'}:scene==='drones'?{num:'02',tag:'РЕАКЦИЯ',objective:'ФЛАГМАН',control:'ПРАВЫЙ КУРОК'}:{num:'00',tag:'ХОЛЛ',objective:'3 ПОРТАЛА',control:'ИССЛЕДОВАНИЕ'};
 const sceneItems=[
  {id:'hub' as const,num:'00',kicker:'ХОЛЛ',name:'Главный павильон',desc:'Ядро · порталы · экспонаты'},
  {id:'robot' as const,num:'01',kicker:'КОНТРОЛЬ',name:'Робот-арена',desc:'Спиннер · энергоячейки · дуэль'},
  {id:'drones' as const,num:'02',kicker:'РЕАКЦИЯ',name:'Дрон-тир',desc:'Точность · серии · флагман'},
  {id:'cargo' as const,num:'03',kicker:'ЛОГИСТИКА',name:'Полигон Лосинка',desc:'Робот 6×6 · захват · доставка'}
 ];
 function switchScene(mode:'hub'|'robot'|'drones'|'cargo'){menuPausedByUs.current=false;game.current?.go(mode);setMenu(false);}
 function openHelp(){if(menuPausedByUs.current){game.current?.resume();menuPausedByUs.current=false;}setMenu(false);setHelp(true);}
 function closeMenu(resumeMission=true){if(resumeMission&&menuPausedByUs.current)game.current?.resume();menuPausedByUs.current=false;setMenu(false);requestAnimationFrame(()=>menuButton.current?.focus());}
 function toggleMenu(){if(menu){closeMenu();return;}menuPausedByUs.current=!hub&&!paused;if(menuPausedByUs.current)game.current?.setPaused(true);setMenu(true);}
 function continueFromMenu(){closeMenu(true);}
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){setError('Не удалось переключить полноэкранный режим: '+String(e));}}
 async function enterVR(){
  if(entering)return;if(!game.current){setError('3D-сцена не запустилась. Обновите страницу и проверьте сообщение об ошибке.');return;}
  setEntering(true);try{if(xr)await game.current.exitVR();else await game.current.enterVR();setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setEntering(false);}
 }
 useEffect(()=>{
  try{
   game.current=createExperience(host.current!,{status:setStatus,scene:setScene,presentation:setPresentation,paused:setPaused,xr:setXR,support:setSupported,error:setError,phase:setPhase,action:setAction,hint:setHint,records:setRecords,autopilot:setAutoDemo,
    diagnostics:d=>setDiagnostics(`${d.xr?'XR':'Экран'} · ${d.fps} кадр/с · ${d.calls} вызовов · ${d.triangles.toLocaleString('ru')} треуг. · ${d.geometries} геом. / ${d.textures} текстур`)});
   const params=new URLSearchParams(location.search),requested=params.get('scene');
   if(params.get('autodemo')==='1')game.current.startCargoDemo();
   else{
    if(params.get('presentation')==='1')game.current.setPresentation(true);
    if(requested&&['hub','robot','drones','cargo'].includes(requested)){
     game.current.go(requested as 'hub'|'robot'|'drones'|'cargo');
     if(requested!=='hub'&&params.get('autostart')==='1')game.current.start();
    }
   }
   if(params.get('clean')==='1')setClean(true);
  }catch(e){setError('Не удалось запустить 3D: '+String(e));}
  return()=>{game.current?.dispose();game.current=null;};
 },[]);
 useEffect(()=>{game.current?.setHelpOpen(help);if(help)dialog.current?.showModal();else dialog.current?.close();},[help]);
 useEffect(()=>{if(xr)setMenu(false);},[xr]);
 useEffect(()=>{game.current?.setDiagnosticsVisible(showDiagnostics);},[showDiagnostics]);
 useEffect(()=>{const onFullscreen=()=>setFullscreen(!!document.fullscreenElement);document.addEventListener('fullscreenchange',onFullscreen);return()=>document.removeEventListener('fullscreenchange',onFullscreen);},[]);
 useEffect(()=>{const update=()=>setOnline(navigator.onLine);window.addEventListener('online',update);window.addEventListener('offline',update);return()=>{window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(help||e.ctrlKey||e.metaKey||e.altKey)return;if((e.key==='m'||e.key==='M')){e.preventDefault();e.stopPropagation();toggleMenu();return;}if(e.key==='Escape'&&menu){e.preventDefault();e.stopPropagation();closeMenu();return;}if(e.repeat)return;if(e.key==='0'){e.preventDefault();switchScene('hub');return;}if(e.key==='1'){e.preventDefault();switchScene('robot');return;}if(e.key==='2'){e.preventDefault();switchScene('drones');return;}if(e.key==='3'){e.preventDefault();switchScene('cargo');return;}if(e.key==='f'||e.key==='F'){e.preventDefault();void toggleFullscreen();}};window.addEventListener('keydown',onKey,true);return()=>window.removeEventListener('keydown',onKey,true);},[menu,hub,paused,help]);
 useEffect(()=>{let active=true;const release=async()=>{try{await wakeLock.current?.release?.();}catch{}wakeLock.current=null;};const acquire=async()=>{if(!active||!presentation||document.visibilityState!=='visible'||!('wakeLock' in navigator)||wakeLock.current)return;try{wakeLock.current=await (navigator as any).wakeLock.request('screen');}catch{}};void acquire();const visibility=()=>{if(document.visibilityState==='visible')void acquire();else void release();};document.addEventListener('visibilitychange',visibility);return()=>{active=false;document.removeEventListener('visibilitychange',visibility);void release();};},[presentation]);
 function newVisitor(){menuPausedByUs.current=false;setHelp(false);setMenu(false);setClean(false);game.current?.nextVisitor();}
 const readyAction=phase==='training'||phase==='ready'||phase==='ended';
 const nextScene=scene==='robot'?'drones':scene==='drones'?'cargo':'hub',nextSceneLabel=scene==='robot'?'Дрон-тир':scene==='drones'?'Полигон Лосинка':'Вернуться в холл';
 return <div className={`experience ${hub?'is-hub':'is-game'}${clean?' clean':''}${xr?' xr-active':''}`} onClick={e=>{const target=e.target as HTMLElement;if(e.detail>0&&!target.closest('dialog'))target.closest('button')?.blur();}}>
  <div ref={host} className="world" aria-label="Интерактивная трёхмерная сцена"/>
  <header className="game-header">
   <button className="wordmark" onClick={()=>game.current?.go('hub')} aria-label="Технопарк РГСУ — в холл"><i>Т.</i><span>ТЕХНОПАРК<small>РГСУ / VR-ПРОСТРАНСТВО</small></span></button>
   <div className="header-tools"><span className="live-badge">ВЕРСИЯ 11.3</span><button className="utility-control" aria-pressed={muted} onClick={()=>setMuted(game.current?.toggleSound()??false)}>{muted?'Звук выкл.':'♪ Звук вкл.'}</button><button onClick={openHelp}>Как играть ?</button><button className="utility-control" aria-pressed={presentation} onClick={()=>game.current?.setPresentation(!presentation)}>{presentation?'Показ ∞ включён':'Режим показа'}</button><button className="clean-toggle utility-control" aria-pressed={clean} onClick={()=>setClean(!clean)}>{clean?'Вернуть интерфейс':'Чистый вид ↗'}</button><button ref={menuButton} className="menu-toggle" aria-expanded={menu} aria-controls="main-command-menu" onClick={toggleMenu}>{menu?'× Закрыть':'☰ Меню'}</button></div>
  </header>
  {menu&&<><button className="menu-scrim" aria-label="Закрыть меню по фону" onClick={()=>closeMenu()}/><aside id="main-command-menu" className={`main-menu scene-${scene}`} aria-label="Главное меню">
   <div className="menu-head"><div><span>ТЕХНОПАРК РГСУ / VR · КОМАНДНЫЙ ЦЕНТР</span><h2>{hub?'Добро пожаловать':'Миссия приостановлена'}</h2><p>{hub?'Выберите пространство и войдите в WebXR — установка приложения не требуется.':'Можно сменить сцену, настроить показ или продолжить ровно с текущего момента.'}</p></div><button className="menu-close" aria-label="Закрыть меню" onClick={()=>closeMenu()}>×</button></div>
   <div className="menu-state"><span className={supported||!online?'ok':''}>{!online?'● ОФЛАЙН · КЭШ':xr?'● VR СЕАНС АКТИВЕН':supported?'● WEBXR ГОТОВ':'● ЭКРАННЫЙ РЕЖИМ'}</span><b>{presentation?'ПОКАЗ ∞':'ОБЫЧНЫЙ РЕЖИМ'}</b></div>
   <section className="menu-current"><div><span>СЕЙЧАС</span><strong>{title}</strong><small>{sceneMeta.num} / {sceneMeta.tag}</small></div><div><span>ЦЕЛЬ</span><strong>{sceneMeta.objective}</strong><small>{sceneMeta.control}</small></div><div className="menu-live"><span>СТАТУС</span><strong>{paused&&!hub?'ПАУЗА':phase==='active'?'МИССИЯ ИДЁТ':phase==='training'?'ОБУЧЕНИЕ':phase==='ended'?'ЗАВЕРШЕНО':phase==='countdown'?'СТАРТ':'ГОТОВО'}</strong><small>{status}</small></div></section>
   <section className="menu-section"><div className="menu-section-title"><h3>Пространства</h3><span>4 СЦЕНЫ · ОДНА VR-СЕССИЯ</span></div><div className="menu-scenes">{sceneItems.map(item=><button key={item.id} data-scene={item.id} className={scene===item.id?'active':''} onClick={()=>switchScene(item.id)}><span className="menu-num">{item.num}</span><span><small>{item.kicker}</small><strong>{item.name}</strong><em>{item.desc}{item.id!=='hub'&&records[item.id]>0?` · рекорд ${records[item.id]}`:''}</em></span><b>{scene===item.id?'ТЕКУЩАЯ':'ОТКРЫТЬ'}</b></button>)}</div></section>
   <section className="menu-section"><div className="menu-section-title"><h3>Режимы</h3><span>ДЛЯ ПРЕЗЕНТАЦИИ</span></div><div className="menu-grid"><button aria-pressed={presentation} onClick={()=>game.current?.setPresentation(!presentation)}><span>∞</span><strong>{presentation?'Показ включён':'Включить показ'}</strong><small>Без таймера и рекордов</small></button><button aria-pressed={autoDemo} onClick={()=>{if(autoDemo)game.current?.stopCargoDemo();else game.current?.startCargoDemo();setMenu(false);}}><span>▶</span><strong>{autoDemo?'Остановить автодемо':'Автодемо Лосинки'}</strong><small>Робот сам доставит 3 груза</small></button><button aria-pressed={muted} onClick={()=>setMuted(game.current?.toggleSound()??false)}><span>{muted?'×':'♪'}</span><strong>{muted?'Включить звук':'Звук включён'}</strong><small>Синтезированные эффекты</small></button><button aria-pressed={clean} onClick={()=>{setClean(!clean);closeMenu(true);}}><span>◫</span><strong>{clean?'Вернуть интерфейс':'Чистый вид'}</strong><small>Только 3D и VR-вход</small></button><button onClick={openHelp}><span>?</span><strong>Инструкция</strong><small>Quest, клавиатура, миссии</small></button></div></section>
   <section className="menu-section"><div className="menu-section-title"><h3>Сеанс</h3><span>БЫСТРЫЕ ДЕЙСТВИЯ</span></div><div className="menu-actions">{!hub&&paused&&<button className="menu-continue" onClick={continueFromMenu}>▶ Продолжить миссию</button>}{!hub&&readyAction&&<button className="menu-primary" onClick={()=>{game.current?.resume();game.current?.start();setMenu(false);}}>▶ Начать раунд</button>}{!hub&&<button onClick={()=>{game.current?.resume();game.current?.train();setMenu(false);}}>◎ Обучение</button>}{!hub&&<button onClick={()=>{game.current?.resume();game.current?.restart();setMenu(false);}}>↻ Сбросить испытание</button>}{hub&&<button onClick={()=>{game.current?.welcome();setMenu(false);}}>✦ Повторить появление «Ядра»</button>}<button onClick={newVisitor}>Новый посетитель</button><button aria-pressed={showDiagnostics} onClick={()=>setShowDiagnostics(!showDiagnostics)}>{showDiagnostics?'⌁ Диагностика включена':'⌁ Диагностика'}</button><button aria-pressed={fullscreen} onClick={toggleFullscreen}>{fullscreen?'⛶ Выйти из полного экрана':'⛶ Полный экран'}</button><a href="?gallery=1">3D-галерея ↗</a></div></section>
   <div className="menu-vr"><div className="menu-vr-copy"><span>IMMERSIVE WEBXR</span><strong>{xr?'Вы находитесь в VR':'Запуск без установки приложения'}</strong></div><button disabled={entering} onClick={enterVR}>{entering?'Подключение…':xr?'Выйти из VR':'◉ Войти в VR'}</button><span>{supported===false?'Откройте HTTPS-ссылку в браузере Quest':supported?'WebXR immersive-vr доступен':'Проверка поддержки WebXR'}</span></div>
   <div className="menu-shortcuts"><span><kbd>M</kbd> меню</span><span><kbd>0–3</kbd> сцены</span><span><kbd>F</kbd> полный экран</span><span><kbd>Q / E</kbd> поворот</span><span><kbd>P</kbd> пауза</span></div>
   <footer><span>ВЕРСИЯ 11.3</span><span>WEBXR / THREE.JS</span><span>QUEST READY</span></footer>
  </aside></>}
  {!clean&&<>
   <main className="game-overlay"><div className="eyebrow"><span/>{hub?'ПРОСТРАНСТВО ВОЗМОЖНОСТЕЙ':cargo?'03 / ЛОГИСТИКА':scene==='robot'?'01 / КОНТРОЛЬ':'02 / РЕАКЦИЯ'}</div>
    <h1>{hub?<>Искусство.<br/>Технологии.<br/><em>Вы внутри.</em></>:title}</h1>
    <p>{hub?'Кинетическое «Ядро», три портала и инженерные испытания. Выберите сцену или исследуйте павильон.':cargo?'Доставьте три груза на зелёную базу. Стрелка над роботом показывает текущую цель. За один рейс — один груз.':scene==='robot'?'Соберите 5 энергоячеек, разрушьте 6 блоков и победите «Бульдозер».':'Шесть зарядов. Бронированные цели. Флагман на 40-й секунде.'}</p>
   </main>
   <aside className="game-status"><span className="status-label">{hub?'ЖИВАЯ ИНСТАЛЛЯЦИЯ':title+(presentation?' · ПОКАЗ БЕЗ ТАЙМЕРА':'')+(autoDemo?' · АВТОДЕМО':'')}</span><strong>{status}</strong>{cargo&&!paused&&phase!=='ready'&&phase!=='ended'&&<p className="cargo-hint">{autoDemo?'Автодемо: робот выполняет полный маршрут доставки без движения камеры наблюдателя.':hint}</p>}</aside>
   {hub?<section className="portal-cards" aria-label="Выберите испытание">
    {sceneItems.slice(1).map(item=><button key={item.id} onClick={()=>switchScene(item.id)}><span className="card-number">{item.num} / {item.kicker}</span><strong>{item.name} <b>↗</b></strong><small>{item.desc}{records[item.id]>0?` · рекорд ${records[item.id]}`:''}</small></button>)}
   </section>:<div className="round-actions">
    {paused?<button className="start-round" onClick={()=>game.current?.resume()}>▶ Продолжить</button>:readyAction?<button className="start-round" onClick={()=>game.current?.start()}>{phase==='training'?'Начать раунд / пропустить урок →':phase==='ended'?'Ещё один раунд →':'Начать раунд →'}</button>:<button onClick={()=>game.current?.setPaused(true)}>Ⅱ Пауза</button>}
    {readyAction&&<button onClick={()=>{game.current?.resume();game.current?.train();}}>Пройти обучение</button>}
   </div>}
   {ground&&<div className="touch-controls" aria-label="Управление роботом">
    {[['↑','w','Вперёд'],['←','a','Повернуть влево'],['↓','s','Назад'],['→','d','Повернуть вправо']].map(([label,key,name])=><button key={key} aria-label={name} disabled={paused||busy&&cargo||autoDemo} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);game.current?.key(key,true);}} onPointerUp={()=>game.current?.key(key,false)} onPointerCancel={()=>game.current?.key(key,false)} onLostPointerCapture={()=>game.current?.key(key,false)}>{label}</button>)}
    <button className="robot-action" disabled={paused||busy&&cargo||autoDemo} onClick={()=>cargo?game.current?.cargoAction():game.current?.spin()}>{cargo?action:'Спиннер'}</button>
   </div>}
   {scene==='drones'&&<button className="reload" disabled={paused} onClick={()=>game.current?.reload()}>Перезарядка / R</button>}
   {!hub&&phase==='ended'&&<section className="result-card" aria-live="polite"><span>ИСПЫТАНИЕ ЗАВЕРШЕНО</span><h2>{title}</h2><p>{status}</p><div><button className="result-primary" onClick={()=>game.current?.start()}>↻ Ещё раунд</button><button onClick={()=>game.current?.go(nextScene as 'hub'|'drones'|'cargo')}>Следующее: {nextSceneLabel} →</button><button onClick={()=>game.current?.go('hub')}>⌂ В холл</button></div></section>}
  </>}
  <footer className="bottom-dock">
   {!clean&&<div className="game-footer"><span>{hub?'WASD — ход · Мышь — осмотр · Q/E — поворот':ground?'W/S — ход · A/D — поворот · Пробел — действие':'Клик по цели — выстрел · R — перезарядка'}</span><nav aria-label="Действия с сеансом">{hub&&<button onClick={()=>game.current?.welcome()}>Появление «Ядра»</button>}<button onClick={newVisitor}>Новый посетитель</button>{!hub&&<><button onClick={()=>{game.current?.resume();game.current?.restart();}}>↻ Сброс</button><button onClick={()=>game.current?.go('hub')}>⌂ Холл</button></>}<a href="?gallery=1">3D-галерея ↗</a></nav></div>}
   <div className="vr-entry"><button disabled={entering} onClick={enterVR}>{entering?'Подключение…':xr?'Выйти из VR':'◉ Войти в VR'}</button><span>{supported===false?'Для VR откройте ссылку в браузере очков':supported?'WEBXR ГОТОВ · ВЕРСИЯ 11.3':'ПРОВЕРКА WEBXR · ВЕРСИЯ 11.3'}</span></div>
  </footer>
  {showDiagnostics&&diagnostics&&!clean&&<output data-diagnostics className="diagnostics">{diagnostics}</output>}
  <dialog ref={dialog} className="help-panel" aria-labelledby="help-title" onCancel={e=>{e.preventDefault();setHelp(false);}}><button className="close-help" onClick={()=>setHelp(false)}>Закрыть ×</button><div className="eyebrow">КРАТКИЙ ИНСТРУКТАЖ</div><h2 id="help-title">Всё под рукой.</h2><div className="help-grid"><article><h3>В очках</h3><p>Левый стик — ходьба в холле или управление наземным роботом. Правый стик — поворот наблюдателя на 30°. Луч и курок — выбор портала, кнопки или светового круга телепортации. Пульт задания расположен слева от игровой зоны.</p><p>Правый курок — спиннер, выстрел или захват. Правая боковая кнопка — перезарядка в тире. Левая боковая кнопка — возврат в холл.</p><p>После системного меню или снятия очков игра приостанавливается. Отпустите стики и нажмите «Продолжить» либо правый курок мимо кнопок. Камера не едет вслед за наземным роботом.</p></article><article><h3>Грузы на полигоне</h3><p>Треугольная стрелка над роботом показывает текущую цель. Подъедьте передней частью к грузу, пока его кольцо не станет зелёным. Отпустите стик, остановитесь и нажмите правый курок. Манипулятор сам захватит груз и уложит на заднюю платформу. Дождитесь завершения движения стрелы.</p><p>После погрузки стрелка переключится на базу, а её контур начнёт пульсировать зелёным. Вернитесь в центр базы и снова нажмите курок. После выгрузки отправляйтесь за следующим грузом. Бетонные барьеры нужно объезжать; грунт замедляет робота, рампа проезжаема.</p><p>На компьютере W/S или ↑/↓ — ход, A/D или ←/→ — поворот, пробел — действие. В тире клик по цели — выстрел, R — перезарядка. P — пауза, пробел — продолжить. На телефоне есть экранные кнопки.</p></article></div><p className="help-note">«Режим показа» отключает таймеры и запись результатов в рекорды. «Новый посетитель» сбрасывает обучение и задания, сохраняя этот режим. Полигон — демонстрационная планировка, робот — стилизованная модель, не точная CAD-реконструкция. Локальные GLB/STL открываются отдельно в 3D-галерее и не синхронизируются между устройствами.</p><button className="start-round" onClick={()=>setHelp(false)}>Всё понятно →</button></dialog>
  {error&&<div className="game-error" role="alert"><button aria-label="Закрыть сообщение" onClick={()=>setError('')}>×</button>{error}</div>}
 </div>;
}
