import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { STLLoader } from 'three/addons/loaders/STLLoader.js';
import { DRACOLoader } from 'three/addons/loaders/DRACOLoader.js';
import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
type Hooks={onVR:(v:boolean)=>void;onState:(v:{scale:number;spin:boolean})=>void;onError:(s:string)=>void};
export type Gallery=ReturnType<typeof createGallery>;
export function createGallery(host:HTMLDivElement,hooks:Hooks){
 const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');renderer.xr.setFramebufferScaleFactor(1);host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#10191f');scene.fog=new T.Fog('#10191f',17,44);
 const camera=new T.PerspectiveCamera(50,1,.05,100);camera.position.set(4.2,3.1,6.5);
 const rig=new T.Group();scene.add(rig);rig.add(camera);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1.5,-2.1);controls.enableDamping=true;controls.minDistance=2.3;controls.maxDistance=15;controls.maxPolarAngle=Math.PI/2-.03;controls.minPolarAngle=.13;
 const environment=new RoomEnvironment(),pmrem=new T.PMREMGenerator(renderer),envMap=pmrem.fromScene(environment,.04);scene.environment=envMap.texture;environment.dispose();pmrem.dispose();scene.environmentIntensity=.65;
 scene.add(new T.HemisphereLight(0xc8edff,0x1b242c,2));const light=new T.DirectionalLight(0xffe8ba,3.5);light.position.set(2,7,5);scene.add(light);const fill=new T.DirectionalLight(0x74c3d9,2.2);fill.position.set(-6,4,-6);scene.add(fill);
 const bronze=new T.MeshStandardMaterial({color:0xd3a759,metalness:.75,roughness:.26});const stone=new T.MeshStandardMaterial({color:0x283138,metalness:.2,roughness:.6});const dark=new T.MeshStandardMaterial({color:0x1c252c,metalness:.35,roughness:.5});const silver=new T.MeshStandardMaterial({color:0xa4b5bc,metalness:.8,roughness:.24});const orange=new T.MeshStandardMaterial({color:0xd6673f,metalness:.5,roughness:.34});const teal=new T.MeshStandardMaterial({color:0x76c6c1,metalness:.7,roughness:.25});
 const mesh=(g:T.BufferGeometry,m:T.Material,parent:T.Object3D=scene,x=0,y=0,z=0)=>{const o=new T.Mesh(g,m);o.position.set(x,y,z);parent.add(o);return o;};
 const box=(w:number,h:number,d:number,m:T.Material,parent:T.Object3D=scene,x=0,y=0,z=0)=>mesh(new T.BoxGeometry(w,h,d),m,parent,x,y,z);
 const floor=mesh(new T.PlaneGeometry(90,90),new T.MeshStandardMaterial({color:0x111a20,roughness:.65,metalness:.28}));floor.rotation.x=-Math.PI/2;
 const grid=new T.GridHelper(70,70,0x3b505a,0x243740);grid.position.y=.004;scene.add(grid);(grid.material as T.Material).transparent=true;(grid.material as T.Material).opacity=.42;
 // Open architectural frame, built from real 3D geometry.
 for(const z of [-7,-12,-17]){box(.1,5,.12,stone,scene,-6,2.5,z);box(.1,5,.12,stone,scene,6,2.5,z);box(12,.12,.12,stone,scene,0,5,z);const glow=new T.MeshBasicMaterial({color:0x71888c});box(.025,4.8,.025,glow,scene,-5.93,2.5,z);box(.025,4.8,.025,glow,scene,5.93,2.5,z);box(11.8,.025,.025,glow,scene,0,4.93,z);}
 box(14,5,.16,dark,scene,0,2.5,-20);
 const pedestal=new T.Group();pedestal.position.z=-2.4;scene.add(pedestal);mesh(new T.CylinderGeometry(1.24,1.3,.16,80),dark,pedestal,0,.08,0);mesh(new T.CylinderGeometry(1.08,1.2,.69,80),stone,pedestal,0,.48,0);mesh(new T.CylinderGeometry(1.1,1.1,.035,80),new T.MeshBasicMaterial({color:0xa9884b}),pedestal,0,.84,0);mesh(new T.CylinderGeometry(1.07,1.07,.06,80),dark,pedestal,0,.88,0);
 const stage=new T.Group();stage.position.set(0,.92,-2.4);scene.add(stage);let current:T.Object3D|null=null,modelScale=1,spinning=!matchMedia('(prefers-reduced-motion: reduce)').matches,disposed=false,sequence=0,mixer:T.AnimationMixer|null=null;
 const interactables:T.Mesh[]=[];const vrOnly=new T.Group();scene.add(vrOnly);vrOnly.visible=false;
 function textPanel(text:string,width:number,height:number,color='#e4ebee',bg?:string){const canvas=document.createElement('canvas');canvas.width=1024;canvas.height=Math.max(128,Math.round(1024*height/width));const ctx=canvas.getContext('2d')!;if(bg){ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);}ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font=`500 ${Math.round(canvas.height*.42)}px Arial`;ctx.fillText(text,512,canvas.height/2,960);const texture=new T.CanvasTexture(canvas);texture.colorSpace=T.SRGBColorSpace;return new T.Mesh(new T.PlaneGeometry(width,height),new T.MeshBasicMaterial({map:texture,transparent:!bg,side:T.DoubleSide}));}
 const wallText=textPanel('ТЕХНОПАРК / VR LAB',5,.48,'#8e9fa6');wallText.position.set(0,3.3,-19.89);scene.add(wallText);
 const label=textPanel('ЭКСПОНАТ / VR LAB',2.2,.17,'#d9bb7a');label.position.set(0,.51,-1.182);scene.add(label);
 function update(){hooks.onState({scale:modelScale,spin:spinning});}
 function applyScale(s:number){modelScale=Math.round(T.MathUtils.clamp(s,.3,3)*10)/10;stage.scale.setScalar(modelScale);update();}
 function resetModel(){stage.rotation.set(0,0,0);stage.scale.setScalar(1);modelScale=1;spinning=false;update();}
 const actions=[['−',()=>applyScale(modelScale-.2)],['+',()=>applyScale(modelScale+.2)],['Вращение',()=>{spinning=!spinning;update();}],['Сброс',resetModel]] as const;
 actions.forEach(([title,fn],i)=>{const p=textPanel(title,i<2?.34:.8,.25,'#f1d695','#27333c');p.position.set(-1.08+i*.67,1.04,-.99);p.rotation.x=-.3;p.userData.action=fn;vrOnly.add(p);interactables.push(p);});
 const vrHint=textPanel('ЛУЧ + КУРОК → КРУГ НА ПОЛУ',2.8,.16,'#aebec5');vrHint.position.set(0,.73,-.98);vrOnly.add(vrHint);
 const pads=[[-2.6,1.4],[2.6,1.4],[-3.2,-3.1],[3.2,-3.1],[0,-5.6],[0,2.5]];
 pads.forEach(([x,z],i)=>{const ring=mesh(new T.RingGeometry(.25,.31,40),new T.MeshBasicMaterial({color:0xb89d60,side:T.DoubleSide}),scene,x,.012,z);ring.rotation.x=-Math.PI/2;const target=mesh(new T.CircleGeometry(.32,32),new T.MeshBasicMaterial({color:0x6f8c91,transparent:true,opacity:.13,side:T.DoubleSide}),vrOnly,x,.016,z);target.rotation.x=-Math.PI/2;target.userData.action=()=>{const p=renderer.xr.getCamera().getWorldPosition(new T.Vector3());rig.position.x+=x-p.x;rig.position.z+=z-p.z;};interactables.push(target);const n=textPanel(String(i+1),.16,.16,'#a7babc');n.rotation.x=-Math.PI/2;n.position.set(x,.02,z);scene.add(n);});
 function sculpture(){const group=new T.Group();const k=mesh(new T.TorusKnotGeometry(.57,.18,160,24,2,3),bronze,group,0,1,0);k.rotation.x=.3;return group;}
 function robot(){const group=new T.Group();mesh(new T.CylinderGeometry(.38,.46,.2,48),silver,group,0,.1,0);box(.42,.55,.44,orange,group,0,.46,0);const shoulder=new T.Group();shoulder.position.set(0,.64,0);shoulder.rotation.z=-.45;group.add(shoulder);let j=mesh(new T.CylinderGeometry(.23,.23,.54,40),silver,shoulder);j.rotation.x=Math.PI/2;box(.24,.9,.3,orange,shoulder,0,.46,0);const elbow=new T.Group();elbow.position.y=.93;elbow.rotation.z=1.3;shoulder.add(elbow);j=mesh(new T.CylinderGeometry(.19,.19,.4,32),silver,elbow);j.rotation.x=Math.PI/2;box(.2,.69,.25,orange,elbow,0,.34,0);mesh(new T.SphereGeometry(.14,24,16),silver,elbow,0,.77,0);for(const x of [-.16,.16]){box(.06,.29,.09,silver,elbow,x,.98,0);box(.1,.05,.09,dark,elbow,x*.72,1.12,0);}return group;}
 function orbit(){const group=new T.Group();mesh(new T.IcosahedronGeometry(.3,1),bronze,group,0,1,0);for(let i=0;i<3;i++){const g=new T.Group();g.position.y=1;g.rotation.set(.5+i*.65,i*.7,.4+i*.65);group.add(g);mesh(new T.TorusGeometry(.86,.026,80,100),i===1?bronze:teal,g);mesh(new T.SphereGeometry(.13,24,16),silver,g,.86,0,0);}return group;}
 // Auxiliary exhibit plinths give the room depth without heavy assets.
 for(const [x,create] of [[-4.4,robot],[4.4,orbit]] as const){mesh(new T.CylinderGeometry(.62,.69,.58,40),stone,scene,x,.29,-7.5);const g=create();g.position.set(x,.6,-7.5);g.scale.setScalar(.7);scene.add(g);}
 function disposeObject(obj:T.Object3D){const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();obj.traverse((child)=>{const m=child as T.Mesh;if(m.geometry)geometries.add(m.geometry);if(m.material)for(const mat of Array.isArray(m.material)?m.material:[m.material]){materials.add(mat);for(const value of Object.values(mat))if(value instanceof T.Texture)textures.add(value);}});geometries.forEach(g=>g.dispose());for(const m of materials)if(![bronze,stone,dark,silver,orange,teal].includes(m as T.MeshStandardMaterial))m.dispose();textures.forEach(t=>t.dispose());}
 function setObject(next:T.Object3D,auto:boolean,animations:T.AnimationClip[]=[]){if(current){stage.remove(current);disposeObject(current);}current=next;stage.add(next);stage.rotation.set(0,0,0);stage.scale.setScalar(1);modelScale=1;spinning=auto;mixer=animations.length?new T.AnimationMixer(next):null;animations.forEach(a=>mixer!.clipAction(a).play());update();}
 function demo(id:string){sequence++;setObject(id==='robot'?robot():id==='orbit'?orbit():sculpture(),!matchMedia('(prefers-reduced-motion: reduce)').matches);}
 demo('sculpture');
 const decoderBase=new URL('./draco/',location.href).href;const manager=new T.LoadingManager();manager.setURLModifier(url=>{if(url.startsWith('blob:')||url.startsWith('data:')||url.startsWith(decoderBase))return url;throw new Error('GLB должен содержать текстуры и геометрию внутри файла.');});
 const draco=new DRACOLoader(manager).setDecoderPath(decoderBase);const loader=new GLTFLoader(manager).setDRACOLoader(draco).setMeshoptDecoder(MeshoptDecoder);
 async function load(buffer:ArrayBuffer,type:string){const ticket=++sequence;let obj:T.Object3D,animations:T.AnimationClip[]=[];
 try{if(type==='stl'){const geometry=new STLLoader().parse(buffer);geometry.computeVertexNormals();obj=new T.Mesh(geometry,silver);}else{if(buffer.byteLength<20||new DataView(buffer).getUint32(0,true)!==0x46546c67)throw new Error('Некорректный GLB. Экспортируйте модель в бинарный glTF (.glb).');const gltf=await loader.parseAsync(buffer,'');obj=gltf.scene;animations=gltf.animations;}
 let count=0;obj.traverse(o=>{const m=o as T.Mesh;if(m.isMesh)count+=(m.geometry.index?.count||m.geometry.attributes.position?.count||0)/3;});if(count===0){disposeObject(obj);throw new Error('В файле не найдена трехмерная геометрия.');}if(count>1000000){disposeObject(obj);throw new Error('Более 1 млн треугольников. Упростите модель перед загрузкой на Quest.');}
 const bounds=new T.Box3().setFromObject(obj),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),max=Math.max(size.x,size.y,size.z);if(!Number.isFinite(max)||max<=0){disposeObject(obj);throw new Error('Модель имеет некорректные размеры.');}const wrap=new T.Group();const factor=1.9/max;obj.position.x-=center.x;obj.position.y-=bounds.min.y;obj.position.z-=center.z;wrap.add(obj);wrap.scale.setScalar(factor);if(ticket!==sequence||disposed){disposeObject(wrap);return;}setObject(wrap,false,animations);
 }catch(e){const msg=(e as Error).message;throw new Error(msg.includes('KTX2')?'Модель использует KTX2-текстуры. Экспортируйте GLB с PNG или JPEG.':msg||'Не удалось прочитать модель. Попробуйте другой GLB или STL.');}}
 const raycaster=new T.Raycaster(),rotation=new T.Matrix4(),controllers:T.Group[]=[];const controllersRoot=new T.Group();rig.add(controllersRoot);controllersRoot.visible=false;const sources=new Map<T.Group,XRInputSource>();
 for(let i=0;i<2;i++){const c=renderer.xr.getController(i);controllersRoot.add(c);controllers.push(c);const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-1)]),new T.LineBasicMaterial({color:0xf4d386}));line.name='ray';line.scale.z=6;c.add(line);c.addEventListener('connected',(event)=>sources.set(c,event.data));c.addEventListener('disconnected',()=>sources.delete(c));c.addEventListener('selectstart',()=>{const hit=hitFor(c);if(hit)hit.object.userData.action?.();});}
 function hitFor(c:T.Group){rotation.identity().extractRotation(c.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(c.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotation);return raycaster.intersectObjects(interactables,false)[0];}
 let savedPosition=new T.Vector3(),savedTarget=new T.Vector3(),snapReady=true;
 renderer.xr.addEventListener('sessionstart',()=>{savedPosition.copy(camera.position);savedTarget.copy(controls.target);controls.enabled=false;rig.position.set(0,0,2.5);rig.rotation.set(0,0,0);camera.position.set(0,0,0);camera.quaternion.identity();vrOnly.visible=true;controllersRoot.visible=true;hooks.onVR(true);});
 renderer.xr.addEventListener('sessionend',()=>{rig.position.set(0,0,0);rig.rotation.set(0,0,0);camera.position.copy(savedPosition);controls.target.copy(savedTarget);controls.enabled=true;controls.update();vrOnly.visible=false;controllersRoot.visible=false;hooks.onVR(false);});
 const resize=new ResizeObserver(()=>{if(renderer.xr.isPresenting)return;const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);});resize.observe(host);
 let previous=0;renderer.setAnimationLoop((time)=>{const dt=previous?Math.min((time-previous)/1000,.05):0;previous=time;if(spinning)stage.rotation.y+=dt*.25;mixer?.update(dt);if(renderer.xr.isPresenting){for(const c of controllers){const hit=hitFor(c);const line=c.getObjectByName('ray')!;line.scale.z=hit?.distance||6;((line as T.Line).material as T.LineBasicMaterial).color.set(hit?0xffffff:0xbfab78);}let axis=0;for(const source of sources.values())if(source.handedness==='right'&&source.gamepad)axis=source.gamepad.axes[2]??source.gamepad.axes[0]??0;if(Math.abs(axis)<.25)snapReady=true;if(snapReady&&Math.abs(axis)>.75){const before=renderer.xr.getCamera().getWorldPosition(new T.Vector3());const delta=-Math.sign(axis)*Math.PI/6;const offset=before.clone().sub(rig.position).applyAxisAngle(new T.Vector3(0,1,0),delta);rig.rotation.y+=delta;rig.position.x=before.x-offset.x;rig.position.z=before.z-offset.z;rig.updateMatrixWorld(true);snapReady=false;}}else controls.update();renderer.render(scene,camera);});
 return {demo,load,scale:applyScale,spin:(v:boolean)=>{spinning=v;update();},resetModel,resetView:()=>{if(renderer.xr.isPresenting)return;camera.position.set(4.2,3.1,6.5);controls.target.set(0,1.5,-2.1);controls.update();},enterVR:async()=>{if(renderer.xr.isPresenting)return;const xr=navigator.xr;if(!xr)throw new Error('WebXR недоступен.');const session=await xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});try{await renderer.xr.setSession(session);}catch(e){await session.end();throw e;}},dispose:()=>{disposed=true;sequence++;renderer.setAnimationLoop(null);renderer.xr.getSession()?.end();resize.disconnect();controls.dispose();draco.dispose();disposeObject(scene);[bronze,stone,dark,silver,orange,teal].forEach(m=>m.dispose());envMap.dispose();renderer.dispose();renderer.domElement.remove();}};
}
