import * as T from 'three';
import {driveRobot,shotHits,falling} from './gameLogic';
import {createArt} from './art';
import {createAudio} from './audio';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
type Mode='hub'|'robot'|'drones';
export function createExperience(host:HTMLElement,hooks:{status:(s:string)=>void;scene:(s:string)=>void;presentation?:(v:boolean)=>void}){
 const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#071722');scene.fog=new T.FogExp2('#071722',.016);const camera=new T.PerspectiveCamera(65,host.clientWidth/host.clientHeight,.05,150),rig=new T.Group();rig.add(camera);scene.add(rig);scene.add(new T.HemisphereLight(0xb9ecff,0x273140,3));const sun=new T.DirectionalLight(0xffcc9b,3);sun.position.set(5,15,8);scene.add(sun);
 const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
 const audioFX=createAudio();
 const worlds={hub:new T.Group(),robot:new T.Group(),drones:new T.Group()};Object.values(worlds).forEach(g=>scene.add(g));const materials:T.Material[]=[],geometries:T.BufferGeometry[]=[],textures:T.Texture[]=[];
 function mat(color:T.ColorRepresentation,metal=.3,glow=false){const m=new T.MeshStandardMaterial({color,metalness:metal,roughness:.4,emissive:glow?color:0,emissiveIntensity:glow?2:0});materials.push(m);return m;}
 const navy=mat('#142d39'),steel=mat('#98aab7',.8),black=mat('#080f17'),cyan=mat('#52ffe0',.2,true),orange=mat('#ff8b3d',.2,true),red=mat('#fa263e'),white=mat('#d9faff');
 function mesh(g:T.Group,geo:T.BufferGeometry,m:T.Material,x=0,y=0,z=0){geometries.push(geo);const o=new T.Mesh(geo,m);o.position.set(x,y,z);g.add(o);return o;}
 const box=(g:T.Group,m:T.Material,x:number,y:number,z:number,w:number,h:number,d:number)=>mesh(g,new T.BoxGeometry(w,h,d),m,x,y,z);
 const cyl=(g:T.Group,m:T.Material,x:number,y:number,z:number,r:number,h:number,n=32)=>mesh(g,new T.CylinderGeometry(r,r,h,n),m,x,y,z);
 function label(g:T.Group,txt:string,x:number,y:number,z:number,w=3,h=.55,color='#baf9ec'){const c=document.createElement('canvas');c.width=1024;c.height=192;const ctx=c.getContext('2d')!;const tex=new T.CanvasTexture(c);textures.push(tex);const m=new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:T.DoubleSide});materials.push(m);const o=mesh(g,new T.PlaneGeometry(w,h),m,x,y,z);let previousText='';function write(s:string){if(s===previousText)return;previousText=s;ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#071923';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 48px Arial';ctx.fillText(s,512,96,990);tex.needsUpdate=true;}write(txt);return {o,write};}
 function ground(g:T.Group,size=40){box(g,navy,0,-.16,-8,size,.3,size);if(g===worlds.hub)return;const grid=new T.GridHelper(size,size/2,0x287477,0x173b48);grid.position.set(0,.004,-8);g.add(grid);geometries.push(grid.geometry);materials.push(grid.material as T.Material);}
 for(const g of Object.values(worlds))ground(g);
 const art=createArt();worlds.hub.add(art.root);
 const hub=worlds.hub;for(let i=0;i<7;i++){let z=4-i*4;for(const x of [-10,10]){box(hub,steel,x,3.3,z,.18,6.6,.18);box(hub,cyan,x,3.3,z+.12,.035,5.8,.025);}box(hub,steel,0,6.6,z,20,.15,.2);box(hub,cyan,0,6.5,z,17,.025,.055);}
 // An open glass pavilion surrounded by a stylized technology campus.
 const glass=new T.MeshPhysicalMaterial({color:0x4dbac9,transparent:true,opacity:.1,roughness:.15,side:T.DoubleSide,depthWrite:false});materials.push(glass);box(hub,glass,-10,3,-8,.04,6,26);box(hub,glass,10,3,-8,.04,6,26);
 for(let i=0;i<24;i++){const side=i%2?1:-1,x=side*(14+(i%4)*3),z=8-Math.floor(i/2)*4,h=3+(i*7%11);box(hub,navy,x,h/2,z,2.5,h,2.7);for(let j=1;j<h;j+=2)box(hub,i%3?cyan:orange,x,j,z+1.36,1.8,.05,.025);}
 for(let i=0;i<14;i++){let x=i%2?11.5:-11.5,z=5-Math.floor(i/2)*4;cyl(hub,steel,x,.5,z,.09,1);mesh(hub,new T.IcosahedronGeometry(.85,0),mat(i%2?'#347e78':'#32755d'),x,1.5,z);}
 label(hub,'Т Е Х Н О П А Р К  /  Р Г С У',0,6.1,-17,9,.65);label(hub,'Я Д Р О  /  КИНЕТИЧЕСКАЯ СКУЛЬПТУРА',0,.7,-8.6,3.6,.32);
 // Curated concentric floor inlays and an architectural sun beyond the pavilion.
 for(const r of [3.2,3.35,6,9]){const line=mesh(hub,new T.TorusGeometry(r,.018,5,96),r<4?cyan:steel,0,.02,-11.5);line.rotation.x=Math.PI/2;}
 const sunset=new T.MeshBasicMaterial({color:0xffbd8b});materials.push(sunset);mesh(hub,new T.SphereGeometry(6,32,16),sunset,0,10,-65);
 for(let i=0;i<9;i++)box(hub,navy,-32+i*8,1+(i%3),-43,6,2+(i%3)*2,8);
 for(const x of [-7.3,7.3]){box(hub,black,x,.35,-1,2,.7,3.6);box(hub,steel,x,.73,-1,2.1,.08,3.6);}
 const actions:T.Object3D[]=[],portals:T.Mesh[]=[];
 function action(o:T.Object3D,f:()=>void){o.userData.action=f;actions.push(o);}
 for(const [x,z] of [[0,-3],[-5,-3],[5,-3],[0,3]]){const pad=cyl(hub,cyan,x,.035,z,.4,.025,32);action(pad,()=>{const head=(renderer.xr.isPresenting?renderer.xr.getCamera():camera).getWorldPosition(new T.Vector3());rig.position.x+=x-head.x;rig.position.z+=z-head.z;audioFX.event('portal');});}
 label(hub,'ЛЕВЫЙ СТИК: ДВИЖЕНИЕ / ПРАВЫЙ: ПОВОРОТ 30°',0,1.2,-1.5,4,.32);label(hub,'ЛУЧ + КУРОК: ПОРТАЛ ИЛИ ТЕЛЕПОРТ НА ПОЛУ',0,.8,-1.5,4,.32);
 function portal(x:number,mode:Mode,title:string,num:string,m:T.Material){const p=new T.Group();p.position.set(x,0,-6);hub.add(p);cyl(p,black,0,.13,0,2,.25);for(const a of [-1,1])box(p,m,a*1.55,1.9,0,.12,3.8,.25);box(p,m,0,3.8,0,3.2,.12,.25);const pm=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,uniforms:{time:{value:0},color:{value:new T.Color(mode==='robot'?'#27ebca':'#ff883a')}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time;uniform vec3 color;void main(){vec2 p=v-.5;float r=length(p*vec2(1.,.75));float a=atan(p.y,p.x);float wave=pow(.5+.5*sin(r*42.-time*2.+a*3.),3.);wave+=.3*pow(.5+.5*sin(a*5.+time*.5+r*22.),8.);float edge=pow(abs(v.x-.5)*2.,5.);gl_FragColor=vec4(color*(.25+wave*.4+edge),.48+edge*.3);}'});materials.push(pm);const surface=mesh(p,new T.PlaneGeometry(3,3.6),pm,0,1.95,0);portals.push(surface);action(surface,()=>go(mode));label(p,title,0,4.3,.05,3.7,.55);label(p,num,0,.65,.08,2.7,.38);}
 portal(-5.2,'robot','КРАСНЫЙ ТРЕУГОЛЬНИК','01 / РОБОТ-АРЕНА',cyan);portal(5.2,'drones','ОХОТА НА ДРОНОВ','02 / ВОЗДУШНЫЙ ТИР',orange);
 const arena=worlds.robot;box(arena,black,0,.06,-7,13,.12,13);for(const x of [-6.7,6.7]){box(arena,steel,x,.4,-7,.15,.8,13.5);box(arena,cyan,x,.85,-7,.06,.05,13.5);}for(const z of [-.3,-13.7]){box(arena,steel,0,.4,z,13.5,.8,.15);box(arena,cyan,0,.85,z,13.5,.05,.06);}label(arena,'ДЕЗИНТЕГРАТОР / КРАСНЫЙ ТРЕУГОЛЬНИК',0,4,-14,9,.6);
 const robot=new T.Group();robot.name='player-robot';arena.add(robot);cyl(robot,black,0,.23,0,.73,.3);cyl(robot,steel,0,.42,0,.67,.15);const ring=new T.Group();robot.add(ring);const rm=mesh(ring,new T.TorusGeometry(.76,.105,6,32),steel,0,.32,0);rm.rotation.x=Math.PI/2;for(const x of [-.85,.85])box(ring,steel,x,.32,0,.3,.2,.28);for(const x of [-.38,.38])box(robot,black,x,.51,0,.2,.035,.38);
 const triangle=new T.Shape();triangle.moveTo(0,-.43);triangle.lineTo(.39,.3);triangle.lineTo(-.39,.3);triangle.closePath();const mark=mesh(robot,new T.ShapeGeometry(triangle),red,0,.507,0);mark.rotation.x=-Math.PI/2;box(robot,black,0,.515,-.06,.065,.02,.25);box(robot,black,0,.516,.14,.065,.02,.06);for(let i=0;i<12;i++){const a=i*Math.PI/6;cyl(robot,black,Math.sin(a)*.59,.514,Math.cos(a)*.59,.025,.025,6);}
 const rival=new T.Group();rival.name='arena-rival';arena.add(rival);box(rival,navy,0,.3,0,1.4,.5,1.2);box(rival,orange,0,.54,0,.9,.06,.7);box(rival,steel,0,.25,-.75,1.6,.25,.35);for(const x of [-.8,.8])for(const z of [-.4,.4]){const wheel=cyl(rival,black,x,.23,z,.23,.14,12);wheel.rotation.z=Math.PI/2;}const rivalName=label(arena,'СОПЕРНИК / БУЛЬДОЗЕР',0,1.3,-11,2.8,.3);rival.visible=false;rivalName.o.visible=false;
 const cells:T.Mesh[]=[],blocks:T.Mesh[]=[];for(let i=0;i<5;i++)cells.push(mesh(arena,new T.OctahedronGeometry(.28),cyan,[-4,3,-3,4,0][i],.6,[-3,-4,-7,-10,-12][i]));for(let i=0;i<6;i++)blocks.push(box(arena,orange,[-4,1,4,-2,2,-4][i],.4,[-5,-6,-8,-10,-12,-12][i],.6,.6,.6));
 cells.forEach(c=>c.name='energy-cell');blocks.forEach(b=>b.name='target-block');
 for(let i=0;i<3;i++){const stripe=box(arena,steel,0,.14,-3-i*4,11,.012,.03);}
 const range=worlds.drones;label(range,'AERIAL LAB / ДРОН-ТРЕНИРОВКА',0,6,-25,11,1);for(let i=0;i<5;i++){box(range,steel,0,.04,-6-i*5,22,.05,.08);for(const x of [-11,11]){box(range,navy,x,4,-6-i*5,.3,8,.3);box(range,orange,x,4,-6-i*5+.17,.08,6,.03);}}
 for(let i=0;i<3;i++){const hoop=mesh(range,new T.TorusGeometry(6+i,.035,6,64),i%2?cyan:orange,0,4,-12-i*7);}
 type Drone={g:T.Group;hit:T.Mesh;phase:number;dead:boolean;velocity:number;respawn:number};const drones:Drone[]=[];
 for(let i=0;i<8;i++){const g=new T.Group();range.add(g);const hit=box(g,steel,0,0,0,.7,.28,.5);box(g,orange,0,0,.28,.4,.08,.06);box(g,black,0,0,0,1.6,.08,.1);box(g,black,0,0,0,.1,.08,1.5);for(const x of [-.65,.65])for(const z of [-.6,.6]){cyl(g,black,x,.06,z,.31,.06,12);const prop=box(g,cyan,x,.1,z,.49,.012,.04);prop.name='propeller';}drones.push({g,hit,phase:i*1.31,dead:false,velocity:0,respawn:0});}
 function gun(){const g=new T.Group();box(g,black,0,0,-.25,.12,.14,.5);box(g,steel,0,.04,-.6,.07,.07,.35);box(g,orange,0,-.03,-.36,.14,.05,.13);const muzzle=mesh(g,new T.IcosahedronGeometry(.12,0),orange,0,.04,-.83);muzzle.name='muzzle-flash';muzzle.visible=false;box(g,cyan,0,.085,-.5,.02,.012,.28);const handle=box(g,navy,0,-.13,-.06,.09,.22,.12);handle.rotation.x=-.3;return g;}
 const desktopGun=gun();camera.add(desktopGun);desktopGun.position.set(.3,-.24,-.25);const flash=mesh(new T.Group(),new T.IcosahedronGeometry(.13,0),orange);camera.add(flash);flash.position.set(.3,-.2,-1);flash.visible=false;
 const sparksGeo=new T.BufferGeometry(),sparkPos=new Float32Array(96*3),sparkVel=new Float32Array(96*3);sparksGeo.setAttribute('position',new T.BufferAttribute(sparkPos,3));geometries.push(sparksGeo);const sparksMat=new T.PointsMaterial({color:0xffc478,size:.08,transparent:true,depthWrite:false});materials.push(sparksMat);const sparks=new T.Points(sparksGeo,sparksMat);sparks.frustumCulled=false;scene.add(sparks);let sparkLife=0;function burst(p:T.Vector3){sparkLife=.7;for(let i=0;i<96;i++){sparkPos.set([p.x,p.y,p.z],i*3);sparkVel.set([(Math.random()-.5)*5,Math.random()*4,(Math.random()-.5)*5],i*3);}sparksGeo.attributes.position.needsUpdate=true;}
 const fadeMat=new T.MeshBasicMaterial({color:0x06131b,transparent:true,opacity:0,depthTest:false,depthWrite:false});materials.push(fadeMat);const fade=mesh(new T.Group(),new T.PlaneGeometry(20,20),fadeMat,0,0,-.3);fade.renderOrder=999;camera.add(fade);let transition=0;
 const hudRoot=new T.Group();scene.add(hudRoot);const hud=label(hudRoot,'',0,2.9,-3,5.5,.55);const guidance=label(hudRoot,'',0,1.85,-3,5.5,.4);const startLabel=label(hudRoot,'НАЧАТЬ РАУНД',0,1.3,-3,2.1,.4);action(startLabel.o,()=>start());
 const back=label(hudRoot,'⌂  ХОЛЛ',-1.5,2.35,-3,1.35,.36);action(back.o,()=>go('hub'));const again=label(hudRoot,'↻  ЗАНОВО',1.5,2.35,-3,1.35,.36);action(again.o,()=>restart());
 const demoLabel=label(hub,'ПРЕЗЕНТАЦИЯ: ВЫКЛ',-2.3,1.6,-1.5,2,.32);action(demoLabel.o,()=>setPresentation(!presentation));const visitorLabel=label(hub,'НОВЫЙ ПОСЕТИТЕЛЬ',2.3,1.6,-1.5,2,.32);action(visitorLabel.o,()=>nextVisitor());const lessonLabel=label(hudRoot,'ОБУЧЕНИЕ',0,.8,-3,1.8,.32);action(lessonLabel.o,()=>train());
 const gameDemoLabel=label(hudRoot,'ПОКАЗ ∞',2,.8,-3,1.5,.32);action(gameDemoLabel.o,()=>setPresentation(!presentation));const newGuest=label(hudRoot,'НОВЫЙ ГОСТЬ',-2,.8,-3,1.5,.32);action(newGuest.o,()=>nextVisitor());
 const handHints:Array<ReturnType<typeof label>>=[];
 const controllers:T.Group[]=[],sources=new Map<T.Group,XRInputSource>(),guns:T.Group[]=[];const raycaster=new T.Raycaster(),rotation=new T.Matrix4();
 function visible(o:T.Object3D){for(let p:T.Object3D|null=o;p;p=p.parent)if(!p.visible)return false;return true;}
 function controllerRay(c:T.Group){c.updateWorldMatrix(true,false);rotation.extractRotation(c.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(c.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotation);}
 for(let i=0;i<2;i++){const c=renderer.xr.getController(i);rig.add(c);controllers.push(c);const hint=label(c,'',0,.12,-.3,.6,.1);hint.o.rotation.x=-.3;handHints.push(hint);const geom=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-12)]);geometries.push(geom);const lm=new T.LineBasicMaterial({color:0x71ffe0,transparent:true,opacity:.6});materials.push(lm);c.add(new T.Line(geom,lm));const weapon=gun();c.add(weapon);guns.push(weapon);c.addEventListener('connected',(e:any)=>{sources.set(c,e.data);weapon.visible=e.data.handedness==='right'&&mode==='drones';});c.addEventListener('disconnected',()=>sources.delete(c));c.addEventListener('selectstart',()=>{controllerRay(c);const hit=raycaster.intersectObjects(actions.filter(visible),false)[0];if(hit){hit.object.userData.action();return;}if(sources.get(c)?.handedness==='right'){if(mode==='robot'){if(ready)start();else spin();}else if(mode==='drones')shoot(raycaster.ray.clone(),c);}});c.addEventListener('squeezestart',()=>{if(sources.get(c)?.handedness==='left')go('hub');else if(mode==='drones')reload();});}
 let presentation=false,training=false,lessonStep=0,lessonTravel=0,lessonTurn=0,lessonSpin=false,health=3,rivalHealth=3,duel=false,impactWait=0,rivalRespawn=0;const learned={move:false,turn:false,spin:false,shoot:false,reload:false};
 let ready=true,countdown=0,combo=0,shots=0,hits=0,turnReady=true,muted=false,notice='',noticeTime=0;let bests:Record<string,number>={robot:0,drones:0};try{bests={...bests,...JSON.parse(localStorage.getItem('technopark-records')||'{}')};}catch{}
 let mode:Mode='hub',seconds=60,score=0,ammo=6,reloading=0,cooldown=0,spinning=false,ended=false,elapsed=0,lastHUD='',flashTime=0;const keys=new Set<string>();
 function sound(f:number,d=.08){audioFX.tone(f,d,'triangle');}
 function notify(message:string){notice=message;noticeTime=2;}
 function setPresentation(value:boolean){presentation=value;gameDemoLabel.write(value?'ПОКАЗ ∞: ВКЛ':'ПОКАЗ ∞: ВЫКЛ');demoLabel.write(value?'ПРЕЗЕНТАЦИЯ: ВКЛ':'ПРЕЗЕНТАЦИЯ: ВЫКЛ');hooks.presentation?.(value);restart();}
 function nextVisitor(){Object.assign(learned,{move:false,turn:false,spin:false,shoot:false,reload:false});go('hub');}
 function train(){if(mode==='hub')return;restart();training=true;ready=false;lessonStep=0;lessonTravel=0;lessonTurn=0;lessonSpin=false;audioFX.unlock();updateHUD();}
 function completeLesson(){restart();notify('ОБУЧЕНИЕ ПРОЙДЕНО / МОЖНО НАЧИНАТЬ');sound(880);updateHUD();}
 function lessonText(){return mode==='robot'?(lessonStep===0?'ОБУЧЕНИЕ 1/2: ПРОЕДЬТЕ И ПОВЕРНИТЕ РОБОТА':'ОБУЧЕНИЕ 2/2: ВКЛЮЧИТЕ СПИННЕР / КУРОК ИЛИ ПРОБЕЛ'):(lessonStep===0?'ОБУЧЕНИЕ 1/2: ПОПАДИТЕ В НЕПОДВИЖНЫЙ ДРОН':'ОБУЧЕНИЕ 2/2: ПЕРЕЗАРЯДИТЕ / БОКОВАЯ КНОПКА ИЛИ R');}
 function start(){if(mode==='hub'||(!training&&!ready&&!ended))return;restart();audioFX.unlock();ready=false;countdown=3;startLabel.o.visible=false;sound(660);updateHUD();}
 function finish(){if(ended)return;ended=true;audioFX.motor(0);const result=mode==='robot'?score*100+Math.ceil(seconds)*10:score;if(!presentation)bests[mode]=Math.max(bests[mode]||0,result);if(!presentation)try{localStorage.setItem('technopark-records',JSON.stringify(bests));}catch{}audioFX.event(mode==='robot'&&score<11?'end':'win');updateHUD();}
 function snap(dir:number){learned.turn=true;const head=(renderer.xr.isPresenting?renderer.xr.getCamera():camera).getWorldPosition(new T.Vector3());const a=-dir*Math.PI/6;rig.position.sub(head).applyAxisAngle(new T.Vector3(0,1,0),a).add(head);rig.rotation.y+=a;}
 function go(next:Mode){transition=.3;audioFX.motor(0);if(next!==mode)audioFX.event('portal');mode=next;keys.clear();Object.entries(worlds).forEach(([name,g])=>g.visible=name===next);rig.position.set(0,0,0);rig.rotation.set(0,0,0);if(!renderer.xr.isPresenting){camera.position.set(0,next==='robot'?7:2.6,next==='robot'?8:7);camera.lookAt(0,next==='robot'?0:2.6,-10);}else{camera.position.set(0,0,0);camera.rotation.set(0,0,0);rig.position.set(0,next==='robot'?1.5:0,next==='robot'?4:1);}desktopGun.visible=next==='drones'&&!renderer.xr.isPresenting;guns.forEach((g,i)=>g.visible=next==='drones'&&sources.get(controllers[i])?.handedness==='right');hudRoot.visible=next!=='hub';hudRoot.position.set(0,next==='robot'?1.5:0,next==='robot'?2:0);guidance.write(next==='robot'?'ЛЕВЫЙ СТИК: РОБОТ · ПРАВЫЙ КУРОК: СПИННЕР':'КУРОК: ОГОНЬ · БОКОВАЯ: ПЕРЕЗАРЯДКА');hooks.scene(next);restart();if(next!=='hub')train();}
 function restart(){keys.clear();turnReady=true;training=false;health=3;rivalHealth=3;duel=false;impactWait=0;rivalRespawn=0;rival.visible=false;rivalName.o.visible=false;rival.position.set(0,0,-11);audioFX.motor(0);sparkLife=0;ready=true;countdown=0;combo=0;shots=0;hits=0;notice='';noticeTime=0;startLabel.o.visible=true;seconds=60;score=0;ammo=6;reloading=0;cooldown=0;spinning=false;ended=false;robot.position.set(0,.02,-2);robot.rotation.set(0,0,0);cells.forEach(c=>c.visible=true);blocks.forEach(c=>c.visible=true);drones.forEach(d=>{d.dead=false;d.velocity=0;d.g.visible=true;d.g.rotation.set(0,0,0);});updateHUD();}
 function spin(){if(mode==='robot'&&!ended&&!ready&&!countdown){spinning=!spinning;learned.spin=true;if(training&&lessonStep===1&&spinning)lessonSpin=true;sound(spinning?400:150);updateHUD();}}
 function reload(){if(mode==='drones'&&!ended&&ammo<6&&!reloading){learned.reload=true;reloading=1.3;audioFX.event('reload');updateHUD();}}
 function shoot(ray:T.Ray,c?:T.Group){if(ready){start();return;}if(ended||countdown||cooldown||reloading)return;if(!ammo){reload();return;}learned.shoot=true;ammo--;shots++;cooldown=.45;flashTime=.065;audioFX.event('shot');const targets=drones.filter(d=>!d.dead&&d.g.visible);let best:Drone|undefined,dist=Infinity;for(const d of targets){const p=d.g.getWorldPosition(new T.Vector3());const along=p.clone().sub(ray.origin).dot(ray.direction);if(shotHits(along,ray.distanceToPoint(p))&&along<dist){best=d;dist=along;}}if(best){best.dead=true;best.velocity=0;best.respawn=2.4;if(training){lessonStep=1;notify('ПОПАДАНИЕ! ТЕПЕРЬ ПЕРЕЗАРЯДИТЕ');}hits++;combo++;const multiplier=Math.min(4,1+Math.floor(combo/3));score+=100*multiplier;burst(best.g.position);audioFX.event('hit');notify('ПОПАДАНИЕ +'+100*multiplier+' / СЕРИЯ ×'+multiplier);const gp=sources.get(c!)?.gamepad as any;gp?.hapticActuators?.[0]?.pulse(.4,100);}else{combo=0;notify('ПРОМАХ / СЕРИЯ СБРОШЕНА');}updateHUD();}
 function updateHUD(){let s=presentation?'ПРЕЗЕНТАЦИЯ ∞ / Выберите сцену':'Ядро / кинетическая инсталляция · Выберите портал';if(mode!=='hub'){const progress=mode==='robot'?(duel?`ДУЭЛЬ · Ваша прочность ${health}/3 · Соперник ${rivalHealth}/3`: `Ячейки ${cells.filter(c=>!c.visible).length}/5 · Блоки ${blocks.filter(c=>!c.visible).length}/6 · ${spinning?'Спиннер ВКЛ':'Спиннер ВЫКЛ'}`):`${score} очков · ${reloading?'Перезарядка…':ammo+'/6 зарядов'} · ×${Math.min(4,1+Math.floor(combo/3))}`;s=training?lessonText():ready?'ГОТОВЫ? НАЖМИТЕ «НАЧАТЬ РАУНД»':countdown>0?'СТАРТ ЧЕРЕЗ '+Math.ceil(countdown):ended?(mode==='robot'?(rivalHealth<=0?'ПОБЕДА В ДУЭЛИ':'ПОПРОБУЙТЕ ЕЩЁ'):`РАУНД ЗАВЕРШЁН · ТОЧНОСТЬ ${shots?Math.round(hits/shots*100):0}%`)+` · ОЧКИ ${mode==='robot'?score*100+Math.ceil(seconds)*10:score} · РЕКОРД ${bests[mode]}`:`${presentation?'ДЕМОНСТРАЦИЯ ∞':Math.ceil(seconds)+' с'} · ${progress}`;}if(s!==lastHUD){lastHUD=s;hooks.status(s);hud.write(s);} }
 function down(e:KeyboardEvent){if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(!e.repeat){if(e.code==='Space'){if(ready&&mode!=='hub')start();else spin();}if(e.key.toLowerCase()==='q')snap(-1);if(e.key.toLowerCase()==='e')snap(1);if(e.key.toLowerCase()==='r')reload();if(e.key==='Escape')go('hub');}}
 const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase()),blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 function click(e:PointerEvent){audioFX.unlock();const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(actions.filter(visible),false)[0];if(hit)hit.object.userData.action();else if(mode==='drones')shoot(raycaster.ray.clone());}let drag:{x:number;y:number;lastX:number;lastY:number;moved:boolean}|null=null;const pointerDown=(e:PointerEvent)=>{if(mode==='hub'){drag={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId);}else click(e);};const pointerMove=(e:PointerEvent)=>{if(!drag||mode!=='hub')return;const dx=e.clientX-drag.lastX,dy=e.clientY-drag.lastY;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5)drag.moved=true;if(drag.moved){camera.rotation.order='YXZ';camera.rotation.y-=dx*.004;camera.rotation.x=T.MathUtils.clamp(camera.rotation.x-dy*.004,-1,1);}drag.lastX=e.clientX;drag.lastY=e.clientY;};const pointerUp=(e:PointerEvent)=>{if(drag&&!drag.moved)click(e);drag=null;};const pointerCancel=()=>{drag=null;};renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',pointerCancel);
 const resize=()=>{if(renderer.xr.isPresenting)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);};const ro=new ResizeObserver(resize);ro.observe(host);renderer.xr.addEventListener('sessionstart',()=>go(mode));renderer.xr.addEventListener('sessionend',()=>{go(mode);resize();});let previous=0;
 renderer.setAnimationLoop((t)=>{const dt=Math.min((t-previous)/1000||.016,.05);previous=t;elapsed+=dt;transition=Math.max(0,transition-dt);fadeMat.opacity=transition/.3;fade.visible=transition>0;art.update(elapsed);noticeTime=Math.max(0,noticeTime-dt);if(mode!=='hub')guidance.write(training?lessonText():noticeTime?notice:(mode==='robot'?'ЛЕВЫЙ СТИК: РОБОТ · ПРАВЫЙ КУРОК: СПИННЕР':'КУРОК: ОГОНЬ · БОКОВАЯ: ПЕРЕЗАРЯДКА'));if(sparkLife>0){sparkLife-=dt;sparks.visible=true;sparksMat.opacity=Math.max(0,sparkLife/.7);for(let i=0;i<96;i++){sparkVel[i*3+1]-=5*dt;for(let j=0;j<3;j++)sparkPos[i*3+j]+=sparkVel[i*3+j]*dt;}sparksGeo.attributes.position.needsUpdate=true;}else sparks.visible=false;
 for(const src of sources.values())if(src.handedness==='right'&&src.gamepad){const a=src.gamepad.axes,x=a.length>=4?a[2]:a[0];if(Math.abs(x)<.3)turnReady=true;else if(Math.abs(x)>.7&&turnReady){snap(Math.sign(x));turnReady=false;}}
 if(countdown>0){const before=Math.ceil(countdown);countdown=Math.max(0,countdown-dt);if(Math.ceil(countdown)!==before)sound(countdown?660:990);}cooldown=Math.max(0,cooldown-dt);flashTime=Math.max(0,flashTime-dt);flash.visible=flashTime>0&&!renderer.xr.isPresenting;guns.forEach(g=>{const m=g.getObjectByName('muzzle-flash');if(m)m.visible=flashTime>0;g.position.z=flashTime>0?.05:0;});desktopGun.position.z=-.25+(flashTime>0?.06:0);portals.forEach(p=>(p.material as T.ShaderMaterial).uniforms.time.value=elapsed);if(mode!=='hub'&&!ended&&!ready&&!countdown&&!training&&!presentation){seconds=Math.max(0,seconds-dt);if(seconds===0)finish();}if(reloading){reloading=Math.max(0,reloading-dt);if(!reloading){ammo=6;if(training&&mode==='drones'&&lessonStep===1)completeLesson();}}
 if(mode==='robot'&&!ended&&!ready&&!countdown){let drive=(keys.has('w')?1:0)-(keys.has('s')?1:0),turn=(keys.has('a')?1:0)-(keys.has('d')?1:0);for(const src of sources.values())if(src.handedness==='left'&&src.gamepad){const a=src.gamepad.axes;const x=a.length>=4?a[2]:a[0],y=a.length>=4?a[3]:a[1];if(Math.abs(y)>.15)drive=-y;if(Math.abs(x)>.15)turn=-x;}audioFX.motor(Math.abs(drive)+(spinning?.7:0));if(Math.abs(drive)>.1)learned.move=true;const moved=driveRobot(robot.position.x,robot.position.z,robot.rotation.y,drive,turn,dt);if(training){lessonTravel+=Math.abs(drive)*3.2*dt;lessonTurn+=Math.abs(turn)*2.4*dt;if(lessonStep===0&&lessonTravel>1&&lessonTurn>.4){lessonStep=1;sound(660);}if(lessonSpin){completeLesson();updateHUD();renderer.render(scene,camera);return;}}robot.rotation.y=moved.yaw;robot.position.x=moved.x;robot.position.z=moved.z;if(spinning)ring.rotation.y+=dt*22;for(const c of cells){c.rotation.y+=dt;c.position.y=.6+Math.sin(elapsed*2+c.position.x)*.12;if(!training&&c.visible&&Math.hypot(c.position.x-robot.position.x,c.position.z-robot.position.z)<1){c.visible=false;score++;sound(700);burst(c.position);notify('ЭНЕРГОЯЧЕЙКА +100');}}for(const b of blocks)if(!training&&b.visible&&spinning&&Math.hypot(b.position.x-robot.position.x,b.position.z-robot.position.z)<1.2){b.visible=false;score++;audioFX.event('hit');burst(b.position);notify('БЛОК УНИЧТОЖЕН +100');}if(!training&&score===11&&!duel){duel=true;rival.visible=true;rivalName.o.visible=true;seconds=Math.max(seconds,35);notify('ФИНАЛ: ПОБЕДИТЕ БУЛЬДОЗЕР СПИННЕРОМ');audioFX.event('portal');}if(duel){impactWait=Math.max(0,impactWait-dt);if(rivalRespawn>0){rivalRespawn-=dt;if(rivalRespawn<=0){rivalHealth=3;rival.visible=true;rival.position.set(0,0,-11);}}else{const delta=robot.position.clone().sub(rival.position);delta.y=0;const distance=delta.length();rival.rotation.y=Math.atan2(-delta.x,-delta.z);if(distance>1.5)rival.position.addScaledVector(delta.normalize(),dt*1.25);if(distance<1.7&&!impactWait){impactWait=1.3;burst(robot.position);audioFX.event('hit');if(spinning){rivalHealth--;notify('ПОПАДАНИЕ ПО СОПЕРНИКУ');}else if(!presentation){health--;notify('УДАР! ВКЛЮЧИТЕ СПИННЕР');}const away=robot.position.clone().sub(rival.position).setY(0).normalize();rival.position.addScaledVector(away,-1.3);rival.position.x=T.MathUtils.clamp(rival.position.x,-5.7,5.7);rival.position.z=T.MathUtils.clamp(rival.position.z,-12.7,-1.3);if(rivalHealth<=0){if(presentation){rival.visible=false;rivalRespawn=3;notify('ПОБЕДА! НОВЫЙ СОПЕРНИК ЧЕРЕЗ 3 С');}else finish();}if(health<=0)finish();}}rivalName.o.position.set(rival.position.x,1.4,rival.position.z);rivalName.write('БУЛЬДОЗЕР '+rivalHealth+'/3');}}
 for(let i=0;i<controllers.length;i++){const hand=sources.get(controllers[i])?.handedness;const hint=handHints[i];const text=hand==='left'?(learned.move?'БОКОВАЯ: ХОЛЛ':'ЛЕВЫЙ СТИК: ДВИЖЕНИЕ'):mode==='drones'?(training&&lessonStep===1?'БОКОВАЯ: ПЕРЕЗАРЯДКА':!learned.shoot?'КУРОК: ВЫСТРЕЛ':!learned.reload?'БОКОВАЯ: ПЕРЕЗАРЯДКА':!learned.turn?'СТИК: ПОВОРОТ 30°':''):mode==='robot'?(!learned.spin?'КУРОК: СПИННЕР':!learned.turn?'СТИК: ПОВОРОТ 30°':''):(!learned.turn?'СТИК: ПОВОРОТ 30°':'КУРОК: ВЫБРАТЬ');hint.o.visible=!!text;hint.write(text);}
 if(mode==='drones')for(let i=0;i<drones.length;i++){const d=drones[i];if(training){d.g.visible=i===0&&!d.dead;if(i===0&&!d.dead){d.g.position.set(0,2.6,-7);d.g.rotation.set(0,0,0);}continue;}for(const part of d.g.children)if(part.name==='propeller')part.rotation.y+=dt*(d.dead?4:35);if(d.dead){const fall=falling(d.g.position.y,d.velocity,dt);d.velocity=fall.velocity;d.g.position.y=fall.y;d.g.rotation.z+=dt*3;d.g.rotation.x+=dt*2;d.respawn-=dt;if(d.g.position.y<.3)d.g.visible=false;if(d.respawn<=0&&!ended){d.dead=false;d.g.visible=true;d.g.rotation.set(0,0,0);}}else if(!ended){d.g.position.set(Math.sin(elapsed*(.35+Math.floor((60-seconds)/20)*.13)+d.phase)*(4+i*.4),2.4+(i%3)*1.4+Math.sin(elapsed+d.phase)*.6,-8-(i%4)*3);d.g.rotation.y=Math.sin(elapsed+d.phase)*.3;}}
 if(mode==='hub'){const headCamera=renderer.xr.isPresenting?renderer.xr.getCamera():camera;const head=headCamera.getWorldPosition(new T.Vector3());let mx=(keys.has('d')?1:0)-(keys.has('a')?1:0),mz=(keys.has('s')?1:0)-(keys.has('w')?1:0);for(const src of sources.values())if(src.handedness==='left'&&src.gamepad){const a=src.gamepad.axes,x=a.length>=4?a[2]:a[0],y=a.length>=4?a[3]:a[1];if(Math.abs(x)>.2)mx=x;if(Math.abs(y)>.2)mz=y;}const direction=headCamera.getWorldDirection(new T.Vector3());direction.y=0;direction.normalize();const side=new T.Vector3(-direction.z,0,direction.x);const move=side.multiplyScalar(mx).addScaledVector(direction,-mz);if(move.length()>.1)learned.move=true;if(move.length()>1)move.normalize();const candidate=head.clone().addScaledVector(move,dt*2);if(Math.hypot(candidate.x,candidate.z+11.5)>3)rig.position.addScaledVector(move,dt*2);rig.position.x=T.MathUtils.clamp(rig.position.x,-8,8);rig.position.z=T.MathUtils.clamp(rig.position.z,-10,5);if(head.z< -5&&head.z> -7){if(Math.abs(head.x+5.2)<1.5)go('robot');else if(Math.abs(head.x-5.2)<1.5)go('drones');}}

 updateHUD();renderer.render(scene,camera);});go('hub');
 return {go,restart,train,setPresentation,nextVisitor,spin,reload,start,turn:snap,toggleSound(){muted=audioFX.toggle();return muted;},key:(k:string,on:boolean)=>on?keys.add(k):keys.delete(k),async enterVR(){audioFX.unlock();if(!navigator.xr)throw new Error('WebXR недоступен. Откройте HTTPS-ссылку в браузере Quest.');if(renderer.xr.isPresenting)return;const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});try{await renderer.xr.setSession(session);}catch(e){await session.end();throw e;}},dispose(){renderer.setAnimationLoop(null);void renderer.xr.getSession()?.end();ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);renderer.domElement.removeEventListener('pointermove',pointerMove);renderer.domElement.removeEventListener('pointerup',pointerUp);renderer.domElement.removeEventListener('pointercancel',pointerCancel);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());art.dispose();environment.dispose();audioFX.dispose();renderer.dispose();renderer.domElement.remove();}};
}
