import * as T from 'three';
import {driveRobot,shotHits,falling} from './gameLogic';
type Mode='hub'|'robot'|'drones';
export function createExperience(host:HTMLElement,hooks:{status:(s:string)=>void;scene:(s:string)=>void}){
 const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(host.clientWidth,host.clientHeight);renderer.xr.enabled=true;renderer.xr.setReferenceSpaceType('local-floor');renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;host.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color('#071722');scene.fog=new T.FogExp2('#071722',.016);const camera=new T.PerspectiveCamera(65,host.clientWidth/host.clientHeight,.05,150),rig=new T.Group();rig.add(camera);scene.add(rig);scene.add(new T.HemisphereLight(0xb9ecff,0x273140,3));const sun=new T.DirectionalLight(0xffcc9b,3);sun.position.set(5,15,8);scene.add(sun);
 const worlds={hub:new T.Group(),robot:new T.Group(),drones:new T.Group()};Object.values(worlds).forEach(g=>scene.add(g));const materials:T.Material[]=[],geometries:T.BufferGeometry[]=[],textures:T.Texture[]=[];
 function mat(color:T.ColorRepresentation,metal=.3,glow=false){const m=new T.MeshStandardMaterial({color,metalness:metal,roughness:.4,emissive:glow?color:0,emissiveIntensity:glow?2:0});materials.push(m);return m;}
 const navy=mat('#142d39'),steel=mat('#98aab7',.8),black=mat('#080f17'),cyan=mat('#52ffe0',.2,true),orange=mat('#ff8b3d',.2,true),red=mat('#fa263e'),white=mat('#d9faff');
 function mesh(g:T.Group,geo:T.BufferGeometry,m:T.Material,x=0,y=0,z=0){geometries.push(geo);const o=new T.Mesh(geo,m);o.position.set(x,y,z);g.add(o);return o;}
 const box=(g:T.Group,m:T.Material,x:number,y:number,z:number,w:number,h:number,d:number)=>mesh(g,new T.BoxGeometry(w,h,d),m,x,y,z);
 const cyl=(g:T.Group,m:T.Material,x:number,y:number,z:number,r:number,h:number,n=32)=>mesh(g,new T.CylinderGeometry(r,r,h,n),m,x,y,z);
 function label(g:T.Group,txt:string,x:number,y:number,z:number,w=3,h=.55,color='#baf9ec'){const c=document.createElement('canvas');c.width=1024;c.height=192;const ctx=c.getContext('2d')!;const tex=new T.CanvasTexture(c);textures.push(tex);const m=new T.MeshBasicMaterial({map:tex,transparent:true,depthWrite:false,side:T.DoubleSide});materials.push(m);const o=mesh(g,new T.PlaneGeometry(w,h),m,x,y,z);function write(s:string){ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#071923';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 48px Arial';ctx.fillText(s,512,96,990);tex.needsUpdate=true;}write(txt);return {o,write};}
 function ground(g:T.Group,size=40){box(g,navy,0,-.16,-8,size,.3,size);const grid=new T.GridHelper(size,size/2,0x287477,0x173b48);grid.position.set(0,.004,-8);g.add(grid);geometries.push(grid.geometry);materials.push(grid.material as T.Material);}
 for(const g of Object.values(worlds))ground(g);
 const hub=worlds.hub;for(let i=0;i<7;i++){let z=4-i*4;for(const x of [-10,10]){box(hub,steel,x,3.3,z,.18,6.6,.18);box(hub,cyan,x,3.3,z+.12,.035,5.8,.025);}box(hub,steel,0,6.6,z,20,.15,.2);box(hub,cyan,0,6.5,z,17,.025,.055);}
 // An open glass pavilion surrounded by a stylized technology campus.
 const glass=new T.MeshPhysicalMaterial({color:0x4dbac9,transparent:true,opacity:.1,roughness:.15,side:T.DoubleSide,depthWrite:false});materials.push(glass);box(hub,glass,-10,3,-8,.04,6,26);box(hub,glass,10,3,-8,.04,6,26);
 for(let i=0;i<24;i++){const side=i%2?1:-1,x=side*(14+(i%4)*3),z=8-Math.floor(i/2)*4,h=3+(i*7%11);box(hub,navy,x,h/2,z,2.5,h,2.7);for(let j=1;j<h;j+=2)box(hub,i%3?cyan:orange,x,j,z+1.36,1.8,.05,.025);}
 for(let i=0;i<14;i++){let x=i%2?11.5:-11.5,z=5-Math.floor(i/2)*4;cyl(hub,steel,x,.5,z,.09,1);mesh(hub,new T.IcosahedronGeometry(.85,0),mat(i%2?'#347e78':'#32755d'),x,1.5,z);}
 label(hub,'Т Е Х Н О П А Р К',0,5.4,-13,8,1);label(hub,'ДВА ПОРТАЛА / ВЫБЕРИТЕ ИСПЫТАНИЕ',0,4.5,-13,7,.45);
 const actions:T.Object3D[]=[],portals:T.Mesh[]=[];
 function action(o:T.Object3D,f:()=>void){o.userData.action=f;actions.push(o);}
 function portal(x:number,mode:Mode,title:string,num:string,m:T.Material){const p=new T.Group();p.position.set(x,0,-8);hub.add(p);cyl(p,black,0,.13,0,2,.25);for(const a of [-1,1])box(p,m,a*1.55,1.9,0,.12,3.8,.25);box(p,m,0,3.8,0,3.2,.12,.25);const pm=new T.ShaderMaterial({transparent:true,side:T.DoubleSide,uniforms:{time:{value:0},color:{value:new T.Color(mode==='robot'?'#27ebca':'#ff883a')}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 v;uniform float time;uniform vec3 color;void main(){vec2 p=v-.5;float r=length(p*vec2(1.,.75));float wave=.5+.5*sin(r*45.-time*3.);float edge=pow(abs(v.x-.5)*2.,5.);gl_FragColor=vec4(color*(.25+wave*.4+edge),.48+edge*.3);}'});materials.push(pm);const surface=mesh(p,new T.PlaneGeometry(3,3.6),pm,0,1.95,0);portals.push(surface);action(surface,()=>go(mode));label(p,title,0,4.3,.05,3.7,.55);label(p,num,0,.65,.08,2.7,.38);}
 portal(-3.8,'robot','КРАСНЫЙ ТРЕУГОЛЬНИК','01 / РОБОТ-АРЕНА',cyan);portal(3.8,'drones','ОХОТА НА ДРОНОВ','02 / ВОЗДУШНЫЙ ТИР',orange);
 const arena=worlds.robot;box(arena,black,0,.06,-7,13,.12,13);for(const x of [-6.7,6.7]){box(arena,steel,x,.4,-7,.15,.8,13.5);box(arena,cyan,x,.85,-7,.06,.05,13.5);}for(const z of [-.3,-13.7]){box(arena,steel,0,.4,z,13.5,.8,.15);box(arena,cyan,0,.85,z,13.5,.05,.06);}label(arena,'ДЕЗИНТЕГРАТОР / КРАСНЫЙ ТРЕУГОЛЬНИК',0,4,-14,9,.6);
 const robot=new T.Group();arena.add(robot);cyl(robot,black,0,.23,0,.73,.3);cyl(robot,steel,0,.42,0,.67,.15);const ring=new T.Group();robot.add(ring);const rm=mesh(ring,new T.TorusGeometry(.76,.105,6,32),steel,0,.32,0);rm.rotation.x=Math.PI/2;for(const x of [-.85,.85])box(ring,steel,x,.32,0,.3,.2,.28);for(const x of [-.38,.38])box(robot,black,x,.51,0,.2,.035,.38);
 const triangle=new T.Shape();triangle.moveTo(0,-.43);triangle.lineTo(.39,.3);triangle.lineTo(-.39,.3);triangle.closePath();const mark=mesh(robot,new T.ShapeGeometry(triangle),red,0,.507,0);mark.rotation.x=-Math.PI/2;box(robot,black,0,.515,-.06,.065,.02,.25);box(robot,black,0,.516,.14,.065,.02,.06);for(let i=0;i<12;i++){const a=i*Math.PI/6;cyl(robot,black,Math.sin(a)*.59,.514,Math.cos(a)*.59,.025,.025,6);}
 const cells:T.Mesh[]=[],blocks:T.Mesh[]=[];for(let i=0;i<5;i++)cells.push(mesh(arena,new T.OctahedronGeometry(.28),cyan,[-4,3,-3,4,0][i],.6,[-3,-4,-7,-10,-12][i]));for(let i=0;i<6;i++)blocks.push(box(arena,orange,[-4,1,4,-2,2,-4][i],.4,[-5,-6,-8,-10,-12,-12][i],.6,.6,.6));
 const range=worlds.drones;label(range,'AERIAL LAB / ДРОН-ТРЕНИРОВКА',0,6,-25,11,1);for(let i=0;i<5;i++){box(range,steel,0,.04,-6-i*5,22,.05,.08);for(const x of [-11,11]){box(range,navy,x,4,-6-i*5,.3,8,.3);box(range,orange,x,4,-6-i*5+.17,.08,6,.03);}}
 type Drone={g:T.Group;hit:T.Mesh;phase:number;dead:boolean;velocity:number;respawn:number};const drones:Drone[]=[];
 for(let i=0;i<8;i++){const g=new T.Group();range.add(g);const hit=box(g,steel,0,0,0,.7,.28,.5);box(g,orange,0,0,.28,.4,.08,.06);box(g,black,0,0,0,1.6,.08,.1);box(g,black,0,0,0,.1,.08,1.5);for(const x of [-.65,.65])for(const z of [-.6,.6]){cyl(g,black,x,.06,z,.31,.06,12);cyl(g,cyan,x,.095,z,.25,.012,12);}drones.push({g,hit,phase:i*1.31,dead:false,velocity:0,respawn:0});}
 function gun(){const g=new T.Group();box(g,black,0,0,-.25,.12,.14,.5);box(g,steel,0,.04,-.6,.07,.07,.35);box(g,orange,0,-.03,-.36,.14,.05,.13);const handle=box(g,navy,0,-.13,-.06,.09,.22,.12);handle.rotation.x=-.3;return g;}
 const desktopGun=gun();camera.add(desktopGun);desktopGun.position.set(.3,-.24,-.25);const flash=mesh(new T.Group(),new T.IcosahedronGeometry(.13,0),orange);camera.add(flash);flash.position.set(.3,-.2,-1);flash.visible=false;
 const hudRoot=new T.Group();scene.add(hudRoot);const hud=label(hudRoot,'',0,2.9,-3,5.5,.55);const back=label(hudRoot,'⌂  ХОЛЛ',-1.5,2.35,-3,1.35,.36);action(back.o,()=>go('hub'));const again=label(hudRoot,'↻  ЗАНОВО',1.5,2.35,-3,1.35,.36);action(again.o,()=>restart());
 const controllers:T.Group[]=[],sources=new Map<T.Group,XRInputSource>(),guns:T.Group[]=[];const raycaster=new T.Raycaster(),rotation=new T.Matrix4();
 function visible(o:T.Object3D){for(let p:T.Object3D|null=o;p;p=p.parent)if(!p.visible)return false;return true;}
 function controllerRay(c:T.Group){c.updateWorldMatrix(true,false);rotation.extractRotation(c.matrixWorld);raycaster.ray.origin.setFromMatrixPosition(c.matrixWorld);raycaster.ray.direction.set(0,0,-1).applyMatrix4(rotation);}
 for(let i=0;i<2;i++){const c=renderer.xr.getController(i);rig.add(c);controllers.push(c);const geom=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(0,0,-12)]);geometries.push(geom);const lm=new T.LineBasicMaterial({color:0x71ffe0,transparent:true,opacity:.6});materials.push(lm);c.add(new T.Line(geom,lm));const weapon=gun();c.add(weapon);guns.push(weapon);c.addEventListener('connected',(e:any)=>{sources.set(c,e.data);weapon.visible=e.data.handedness==='right'&&mode==='drones';});c.addEventListener('disconnected',()=>sources.delete(c));c.addEventListener('selectstart',()=>{controllerRay(c);const hit=raycaster.intersectObjects(actions.filter(visible),false)[0];if(hit){hit.object.userData.action();return;}if(sources.get(c)?.handedness==='right'){if(mode==='robot')spin();else if(mode==='drones')shoot(raycaster.ray.clone(),c);}});c.addEventListener('squeezestart',()=>{if(mode==='drones')reload();});}
 let mode:Mode='hub',seconds=60,score=0,ammo=6,reloading=0,cooldown=0,spinning=false,ended=false,elapsed=0,lastHUD='',flashTime=0;const keys=new Set<string>();let audio:AudioContext|undefined;
 function sound(f:number,d=.08){try{audio??=new AudioContext();void audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.type='triangle';osc.frequency.setValueAtTime(f,audio.currentTime);osc.frequency.exponentialRampToValueAtTime(70,audio.currentTime+d);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+d);}catch{}}
 function go(next:Mode){mode=next;keys.clear();Object.entries(worlds).forEach(([name,g])=>g.visible=name===next);rig.position.set(0,0,0);rig.rotation.set(0,0,0);if(!renderer.xr.isPresenting){camera.position.set(next==='robot'?0:2,next==='robot'?7:2.8,next==='robot'?8:6);camera.lookAt(next==='hub'?1:0,next==='robot'?0:2,-8);}else{camera.position.set(0,0,0);camera.rotation.set(0,0,0);rig.position.set(0,next==='robot'?1.5:0,next==='robot'?4:1);}desktopGun.visible=next==='drones'&&!renderer.xr.isPresenting;guns.forEach((g,i)=>g.visible=next==='drones'&&sources.get(controllers[i])?.handedness==='right');hudRoot.visible=next!=='hub';hudRoot.position.set(0,next==='robot'?1.5:0,next==='robot'?2:0);hooks.scene(next);restart();}
 function restart(){seconds=60;score=0;ammo=6;reloading=0;cooldown=0;spinning=false;ended=false;robot.position.set(0,.02,-2);robot.rotation.set(0,0,0);cells.forEach(c=>c.visible=true);blocks.forEach(c=>c.visible=true);drones.forEach(d=>{d.dead=false;d.velocity=0;d.g.visible=true;d.g.rotation.set(0,0,0);});updateHUD();}
 function spin(){if(mode==='robot'&&!ended){spinning=!spinning;sound(spinning?400:150);updateHUD();}}
 function reload(){if(mode==='drones'&&!ended&&ammo<6&&!reloading){reloading=1.3;sound(240,.12);updateHUD();}}
 function shoot(ray:T.Ray,c?:T.Group){if(ended||cooldown||reloading)return;if(!ammo){reload();return;}ammo--;cooldown=.45;flashTime=.065;sound(100,.15);const targets=drones.filter(d=>!d.dead&&d.g.visible);let best:Drone|undefined,dist=Infinity;for(const d of targets){const p=d.g.getWorldPosition(new T.Vector3());const along=p.clone().sub(ray.origin).dot(ray.direction);if(shotHits(along,ray.distanceToPoint(p))&&along<dist){best=d;dist=along;}}if(best){best.dead=true;best.velocity=0;best.respawn=2.4;score+=100;const gp=sources.get(c!)?.gamepad as any;gp?.hapticActuators?.[0]?.pulse(.4,100);}updateHUD();}
 function updateHUD(){const s=mode==='hub'?'Выберите световой портал':mode==='robot'?(ended?(score===11?'Испытание пройдено!':'Время вышло'):`${Math.ceil(seconds)} с`)+` · Ячейки ${cells.filter(c=>!c.visible).length}/5 · Блоки ${blocks.filter(c=>!c.visible).length}/6 · Спиннер ${spinning?'ВКЛ':'ВЫКЛ'}`:(ended?'Раунд окончен':`${Math.ceil(seconds)} с`)+` · Очки ${score} · ${reloading?'Перезарядка…':`Заряды ${ammo}/6`}`;if(s!==lastHUD){lastHUD=s;hooks.status(s);hud.write(s);}}
 function down(e:KeyboardEvent){if([' ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(!e.repeat){if(e.code==='Space')spin();if(e.key.toLowerCase()==='r')reload();if(e.key==='Escape')go('hub');}}
 const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase()),blur=()=>keys.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);
 function click(e:PointerEvent){const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(actions.filter(visible),false)[0];if(hit)hit.object.userData.action();else if(mode==='drones')shoot(raycaster.ray.clone());}renderer.domElement.addEventListener('pointerdown',click);
 const resize=()=>{if(renderer.xr.isPresenting)return;camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight);};const ro=new ResizeObserver(resize);ro.observe(host);renderer.xr.addEventListener('sessionstart',()=>go(mode));renderer.xr.addEventListener('sessionend',()=>{go(mode);resize();});let previous=0;
 renderer.setAnimationLoop((t)=>{const dt=Math.min((t-previous)/1000||.016,.05);previous=t;elapsed+=dt;cooldown=Math.max(0,cooldown-dt);flashTime=Math.max(0,flashTime-dt);flash.visible=flashTime>0&&!renderer.xr.isPresenting;portals.forEach(p=>(p.material as T.ShaderMaterial).uniforms.time.value=elapsed);if(mode!=='hub'&&!ended){seconds=Math.max(0,seconds-dt);if(seconds===0)ended=true;}if(reloading){reloading=Math.max(0,reloading-dt);if(!reloading)ammo=6;}
 if(mode==='robot'&&!ended){let drive=(keys.has('w')?1:0)-(keys.has('s')?1:0),turn=(keys.has('a')?1:0)-(keys.has('d')?1:0);for(const src of sources.values())if(src.handedness==='left'&&src.gamepad){const a=src.gamepad.axes;const x=a.length>=4?a[2]:a[0],y=a.length>=4?a[3]:a[1];if(Math.abs(y)>.15)drive=-y;if(Math.abs(x)>.15)turn=-x;}const moved=driveRobot(robot.position.x,robot.position.z,robot.rotation.y,drive,turn,dt);robot.rotation.y=moved.yaw;robot.position.x=moved.x;robot.position.z=moved.z;if(spinning)ring.rotation.y+=dt*22;for(const c of cells){c.rotation.y+=dt;c.position.y=.6+Math.sin(elapsed*2+c.position.x)*.12;if(c.visible&&Math.hypot(c.position.x-robot.position.x,c.position.z-robot.position.z)<1){c.visible=false;score++;sound(700);}}for(const b of blocks)if(b.visible&&spinning&&Math.hypot(b.position.x-robot.position.x,b.position.z-robot.position.z)<1.2){b.visible=false;score++;sound(130);}if(score===11)ended=true;}
 if(mode==='drones')for(let i=0;i<drones.length;i++){const d=drones[i];if(d.dead){const fall=falling(d.g.position.y,d.velocity,dt);d.velocity=fall.velocity;d.g.position.y=fall.y;d.g.rotation.z+=dt*3;d.g.rotation.x+=dt*2;d.respawn-=dt;if(d.g.position.y<.3)d.g.visible=false;if(d.respawn<=0&&!ended){d.dead=false;d.g.visible=true;d.g.rotation.set(0,0,0);}}else if(!ended){d.g.position.set(Math.sin(elapsed*.35+d.phase)*(4+i*.4),2.4+(i%3)*1.4+Math.sin(elapsed+d.phase)*.6,-8-(i%4)*3);d.g.rotation.y=Math.sin(elapsed+d.phase)*.3;}}
 if(mode==='hub'&&renderer.xr.isPresenting){const head=renderer.xr.getCamera().getWorldPosition(new T.Vector3());for(const src of sources.values())if(src.handedness==='left'&&src.gamepad){const a=src.gamepad.axes,y=a.length>=4?a[3]:a[1],x=a.length>=4?a[2]:a[0];if(Math.abs(y)>.2)rig.position.z=T.MathUtils.clamp(rig.position.z+y*dt*2,-7,8);if(Math.abs(x)>.2)rig.position.x=T.MathUtils.clamp(rig.position.x+x*dt*2,-8,8);}if(head.z< -6.7){if(Math.abs(head.x+3.8)<1.5)go('robot');else if(Math.abs(head.x-3.8)<1.5)go('drones');}}
 updateHUD();renderer.render(scene,camera);});go('hub');
 return {go,restart,spin,reload,key:(k:string,on:boolean)=>on?keys.add(k):keys.delete(k),async enterVR(){if(!navigator.xr)throw new Error('WebXR недоступен. Откройте HTTPS-ссылку в браузере Quest.');if(renderer.xr.isPresenting)return;const session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor']});try{await renderer.xr.setSession(session);}catch(e){await session.end();throw e;}},dispose(){renderer.setAnimationLoop(null);void renderer.xr.getSession()?.end();ro.disconnect();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',click);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());void audio?.close();renderer.dispose();renderer.domElement.remove();}};
}
