/** Rebuild compact rigid meshes from attributed source GLBs. No new runtime dependency. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {inflateSync} from 'node:zlib';
import * as T from 'three';
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader.js';
import {mergeGeometries,mergeVertices} from 'three/examples/jsm/utils/BufferGeometryUtils.js';
const directory=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../assets/models');
const readGLB=async name=>{const b=await fs.readFile(path.join(directory,'source',name+'.glb'));const length=b.readUInt32LE(12);return {json:JSON.parse(b.subarray(20,20+length).toString()),bin:b.subarray(28+length),bytes:b};};
function packGLB(json,bin){const j=Buffer.from(JSON.stringify(json)),jl=Math.ceil(j.length/4)*4,bl=Math.ceil(bin.length/4)*4,b=Buffer.alloc(28+jl+bl);b.write('glTF');b.writeUInt32LE(2,4);b.writeUInt32LE(b.length,8);b.writeUInt32LE(jl,12);b.write('JSON',16);b.fill(32,20,20+jl);j.copy(b,20);b.writeUInt32LE(bl,20+jl);b.write('BIN\0',24+jl);bin.copy(b,28+jl);return b;}
// Decode the tiny, un-interlaced RGB/RGBA PNG palette. It is baked to vertices, not shipped to the GPU.
function pngPixels(buffer){let w,h,type,depth,compressed=[];for(let p=8;p<buffer.length;){const n=buffer.readUInt32BE(p),kind=buffer.toString('ascii',p+4,p+8),v=buffer.subarray(p+8,p+8+n);if(kind==='IHDR'){w=v.readUInt32BE(0);h=v.readUInt32BE(4);depth=v[8];type=v[9];if(v[12])throw Error('Interlaced palette unsupported');}if(kind==='IDAT')compressed.push(v);p+=12+n;}if(depth!==8||![2,6].includes(type))throw Error('Expected RGB(A) palette');const channels=type===6?4:3,raw=inflateSync(Buffer.concat(compressed)),stride=w*channels,out=Buffer.alloc(stride*h);let p=0;const paeth=(a,b,c)=>{const v=a+b-c,x=Math.abs(v-a),y=Math.abs(v-b),z=Math.abs(v-c);return x<=y&&x<=z?a:y<=z?b:c;};for(let y=0;y<h;y++){const filter=raw[p++];for(let x=0;x<stride;x++){const i=y*stride+x,a=x>=channels?out[i-channels]:0,b=y?out[i-stride]:0,c=y&&x>=channels?out[i-stride-channels]:0;out[i]=(raw[p++]+(filter===1?a:filter===2?b:filter===3?Math.floor((a+b)/2):filter===4?paeth(a,b,c):0))&255;}}return {w,h,channels,data:out};}
const encoded=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength).toString('base64');
function serialize(geometry){geometry.deleteAttribute('uv');geometry=mergeVertices(geometry,1e-5);geometry.computeBoundingSphere();return {position:encoded(geometry.attributes.position.array),normal:encoded(geometry.attributes.normal.array),color:geometry.attributes.color?encoded(geometry.attributes.color.array):undefined,index:encoded(new Uint16Array(geometry.index.array)),vertices:geometry.attributes.position.count,triangles:geometry.index.count/3};}
const gunSource=await readGLB('mossberg'),gun=await new GLTFLoader().parseAsync(gunSource.bytes.buffer.slice(gunSource.bytes.byteOffset,gunSource.bytes.byteOffset+gunSource.bytes.length),'');gun.scene.updateMatrixWorld(true);
const gunPieces=[],lengthScale=1.12/6.024581638761;
gun.scene.traverse(o=>{if(!o.isSkinnedMesh)return;o.skeleton.update();const g=o.geometry,idx=g.index,skin=g.attributes.skinIndex,n=g.attributes.normal,p=new T.Vector3(),normal=new T.Vector3(),normalMatrix=new T.Matrix3().getNormalMatrix(o.matrixWorld);for(const joint of [0,1,2]){const positions=[],normals=[];for(let i=0;i<idx.count;i+=3){const ids=[idx.getX(i),idx.getX(i+1),idx.getX(i+2)];if(skin.getX(ids[0])!==joint)continue;for(const id of ids){o.getVertexPosition(id,p);p.applyMatrix4(o.matrixWorld);positions.push(p.z*lengthScale,(p.y-.9)*lengthScale,-(p.x+.75)*lengthScale);normal.fromBufferAttribute(n,id).applyMatrix3(normalMatrix).normalize();normals.push(normal.z,normal.y,-normal.x);}}if(!positions.length)continue;const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new T.Float32BufferAttribute(normals,3));gunPieces.push({name:joint===2?'shotgun-pump':joint===1?'shotgun-trigger':'shotgun-body',material:o.material.name==='shotgun_body'?'gunSteel':'gunPolymer',...serialize(geo)});}});
const source=await readGLB('drone'),j=source.json,im=j.bufferViews[j.images[0].bufferView],palette=pngPixels(source.bin.subarray(im.byteOffset,im.byteOffset+im.byteLength));
// Keep UV attributes until the texture palette has been sampled.
delete j.images;delete j.textures;delete j.samplers;for(const m of j.materials)delete m.pbrMetallicRoughness.baseColorTexture;
const raw=packGLB(j,source.bin),drone=await new GLTFLoader().parseAsync(raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.length),'');drone.scene.updateMatrixWorld(true);
const bodies=[],rotors=[],scratch=new T.Vector3(),color=new T.Color();
drone.scene.traverse(o=>{if(!o.isMesh)return;const g=o.geometry.clone().applyMatrix4(o.matrixWorld),uv=g.attributes.uv,colors=[];for(let i=0;i<uv.count;i++){const x=Math.max(0,Math.min(palette.w-1,Math.floor(uv.getX(i)*palette.w))),y=Math.max(0,Math.min(palette.h-1,Math.floor(uv.getY(i)*palette.h))),p=(y*palette.w+x)*palette.channels;color.setRGB(palette.data[p]/255,palette.data[p+1]/255,palette.data[p+2]/255,T.SRGBColorSpace);if(Math.max(color.r,color.g,color.b)<.015)color.setRGB(.035,.044,.051);colors.push(color.r,color.g,color.b);}g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.translate(0,0,.134);g.scale(2.45,2.45,2.45);if(o.name.startsWith('Rotor_')){g.computeBoundingBox();g.boundingBox.getCenter(scratch);const center=scratch.toArray();g.translate(-scratch.x,-scratch.y,-scratch.z);rotors.push({name:o.name,center,geometry:g});}else bodies.push(g);});
const rotor=serialize(rotors[0].geometry),dronePieces=[{name:'drone-body',material:'drone',...serialize(mergeGeometries(bodies))},{name:'drone-rotors',material:'drone',centers:rotors.map(r=>r.center),...rotor}];
const result={gun:gunPieces,drone:dronePieces};await fs.writeFile(path.join(directory,'showcase.json'),JSON.stringify(result));console.log(JSON.stringify({gun:gunPieces.map(p=>[p.name,p.triangles]),drone:dronePieces.map(p=>[p.name,p.triangles]),bytes:JSON.stringify(result).length}));
